package org.redukti.tools;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.redukti.examples.ExampleFinder;
import org.redukti.importers.obench.OpticalBenchDataImporter;
import org.redukti.optim.OptimizationTrial;
import org.redukti.optim.VarThickness;
import org.redukti.spec.Prescription;
import org.redukti.util.Args;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

/** Running a [trial n] from LensTool2, and the --optimize argument that asks for it. */
class OptimizationTrialRunTest {

    private static final String OTUS = "Examples/jfotoptix/cosina-otus-ml-50mm-f1.4/JP2026-105585_Example01.txt";

    private static final String TRIALS = """

            [trial 3]
            description   Back focus for contrast
            fields        0
            frequencies   20
            vary thicknesses  25
            goal contrast     20
            goal contrast     sampling 3 6

            [trial 4]
            description   The same, reported separately
            outdir        trials/back focus
            fields        0
            frequencies   20
            vary thicknesses  25
            goal contrast     20
            goal contrast     sampling 3 6
            """;

    private static Path otus(Path dir) throws Exception {
        Path spec = dir.resolve("otus.txt");
        Files.writeString(spec, Files.readString(Path.of(ExampleFinder.geoPathToExample(OTUS))) + TRIALS);
        return spec;
    }

    private static Prescription prescription(String text) throws Exception {
        var specs = new OpticalBenchDataImporter.LensSpecifications();
        specs.parse_buffer(text);
        return Prescription.build_prescription(specs, true, false, false);
    }

    @Test
    void optimizeTakesAnOptionalTrialNumber() {
        var trial = Args.parseArguments(new String[]{"--specfile", "lens.txt", "--optimize", "2"});
        assertEquals(2, trial.optimize_trial);
        assertFalse(trial.optimize);

        var routine = Args.parseArguments(new String[]{"--specfile", "lens.txt", "--optimize", "--mtf", "10,20"});
        assertTrue(routine.optimize);
        assertNull(routine.optimize_trial);
        assertArrayEquals(new int[]{10, 20}, routine.mtf_freqs);

        var last = Args.parseArguments(new String[]{"--specfile", "lens.txt", "--optimize"});
        assertTrue(last.optimize);

        var e = assertThrows(IllegalArgumentException.class,
                () -> Args.parseArguments(new String[]{"--optimize", "two"}));
        assertTrue(e.getMessage().contains("[trial n]"), e.getMessage());
    }

    @Test
    void writesToTheTrialsOwnDirectory(@TempDir Path dir) throws Exception {
        Path spec = otus(dir);
        Args arguments = Args.parseArguments(new String[]{"--specfile", spec.toString(), "--optimize", "4"});
        LensTool2.runOptimizationTrial(Files.readString(spec), arguments);
        Path output = dir.resolve("trials").resolve("back focus").resolve("otus-trial4.txt");
        assertTrue(Files.exists(output));
        assertEquals(output.toAbsolutePath(), Path.of(arguments.specfile).toAbsolutePath());
        assertNull(arguments.outdir);
    }

    @Test
    void commandLineOutdirTakesPrecedence(@TempDir Path dir) throws Exception {
        Path spec = otus(dir);
        Path elsewhere = dir.resolve("elsewhere");
        Args arguments = Args.parseArguments(new String[]{"--specfile", spec.toString(),
                "--outdir", elsewhere.toString(), "--optimize", "4"});
        LensTool2.runOptimizationTrial(Files.readString(spec), arguments);
        assertTrue(Files.exists(elsewhere.resolve("otus-trial4.txt")));
        assertFalse(Files.exists(dir.resolve("trials")));
    }

    @Test
    void writesThePrescriptionFollowedByTheTrial(@TempDir Path dir) throws Exception {
        Path spec = otus(dir);
        Args arguments = Args.parseArguments(new String[]{"--specfile", spec.toString(), "--optimize", "3"});

        String optimized = LensTool2.runOptimizationTrial(Files.readString(spec), arguments);

        // Without an outdir the optimized prescription is written next to the input, and
        // the rest of the run is pointed at it.
        Path output = dir.resolve("otus-trial3.txt");
        assertEquals(output.toAbsolutePath(), Path.of(arguments.specfile).toAbsolutePath());
        assertEquals(optimized, Files.readString(output));

        // Beam42's own prescription, then the trial that ran as the builder writes it, and no
        // other trial.
        assertTrue(optimized.startsWith("[descriptive data]\n"));
        assertTrue(optimized.contains("Generated by Beam42"));
        assertTrue(optimized.endsWith("\n" + OptimizationTrial.read(Files.readString(spec), 3, true).toTrial(3)));
        assertFalse(optimized.contains("[trial 4]"));

        // The back focus moved, and the trial carried over still names it: it can be run
        // again on the output as it stands.
        var prescription = prescription(optimized);
        assertNotEquals(18.665, prescription._surfaces[25]._thickness);
        var again = OptimizationTrial.read(optimized, 3, true);
        var variable = (VarThickness) again.build().variables()[0];
        assertEquals(25, variable._surface_id);
        variable.read_from_prescription();
        assertEquals(prescription._surfaces[25]._thickness, variable.get_unscaled_value());
    }

    /** A zoom of two configurations, 0 and 1, whose surface 8 varies between them. */
    private static final String ZOOM = "Examples/jfotoptix/canon-rf70-200mm-f2.8LZ/US20250155694_Example01P.txt";

    /** One configuration at a time: the tele stage starts from the wide stage's result. */
    private static final String PIPELINE = """

            [trial 5]
            description       Wide end
            configuration     0
            fields            0
            frequencies       20
            vary thicknesses  8
            goal paraxial     bfl 40

            [trial 6]
            description       Tele end
            configuration     1
            fields            0
            frequencies       20
            vary thicknesses  8
            goal paraxial     bfl 40

            [pipeline 7]
            description       Wide, then tele
            outdir            trials/zoom
            trials            5 6
            """;

    @Test
    void runsAPipelineStageByStage(@TempDir Path dir) throws Exception {
        Path spec = dir.resolve("zoom.txt");
        Files.writeString(spec, Files.readString(Path.of(ExampleFinder.geoPathToExample(ZOOM))) + PIPELINE);
        Args arguments = Args.parseArguments(new String[]{"--specfile", spec.toString(), "--optimize", "7"});

        String optimized = LensTool2.runOptimizationTrial(Files.readString(spec), arguments);

        // One result, in the pipeline's own directory, and the rest of the run uses it.
        Path output = dir.resolve("trials").resolve("zoom").resolve("zoom-pipeline7.txt");
        assertTrue(Files.exists(output));
        assertEquals(output.toAbsolutePath(), Path.of(arguments.specfile).toAbsolutePath());
        assertEquals(optimized, Files.readString(output));

        // Each stage moved its own configuration's column, so both changed.
        var prescription = prescription(optimized);
        assertNotEquals(8.46, prescription._surfaces[8]._thickness_by_scenario[0]);
        assertNotEquals(13.14, prescription._surfaces[8]._thickness_by_scenario[1]);

        // The result carries the pipeline and both its trials, so it can run again as it stands.
        var again = OptimizationTrial.readPipeline(optimized, 7);
        assertArrayEquals(new int[]{5, 6}, again.trials());
        assertEquals("trials/zoom", again.outdir());
        for (int stage : again.trials())
            assertEquals(8, ((VarThickness) OptimizationTrial.read(optimized, stage, true)
                    .build().variables()[0])._surface_id);
    }
}
