package org.redukti.rayoptics.upstream;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.redukti.rayoptics.elem.profiles.EvenPolynomial;
import org.redukti.rayoptics.elem.profiles.RadialPolynomial;
import org.redukti.rayoptics.optical.OpticalModel;
import org.redukti.rayoptics.parax.ThirdOrder;
import org.redukti.rayoptics.parax.ThirdOrderData;
import org.redukti.rayoptics.raytr.Trace;
import org.redukti.rayoptics.raytr.VigCalc;
import org.redukti.rayoptics.seq.SurfaceData;
import org.redukti.rayoptics.specs.FieldSpec;
import org.redukti.rayoptics.specs.ImageKey;
import org.redukti.rayoptics.specs.PupilSpec;
import org.redukti.rayoptics.specs.ValueKey;
import org.redukti.rayoptics.specs.WvlSpec;
import org.redukti.rayoptics.specs.WvlWt;
import org.redukti.rayoptics.util.Pair;

/**
 * Upstream regression test for US004717245_Example02P.txt.
 * <p>
 * Generated by JavaTestWriter - do not edit, regenerate.
 * Reference values were captured from upstream ray-optics running the
 * equivalent generated Python model.
 */
public class US004717245Example02PUpstreamTest {

    /** Relative tolerance, floored so near-zero values do not demand exactness. */
    private static void assertClose(String what, double expected, double actual, double rel) {
        double tol = Math.max(rel, Math.abs(expected) * rel);
        Assertions.assertEquals(expected, actual, tol, what);
    }

    private static OpticalModel build() {
        var opm = new OpticalModel();
        var sm = opm.seq_model;
        var osp = opm.optical_spec;
        osp.pupil = new PupilSpec(osp, new Pair<>(ImageKey.Image, ValueKey.Fnum), 1.0d);
        osp.fov = new FieldSpec(osp, new Pair<>(ImageKey.Object, ValueKey.Angle), 22.6d, new double[]{0.0d, 0.707d, 1.0d}, true, false);
        osp.wvls = new WvlSpec(new WvlWt[]{new WvlWt(587.5618d, 1.0d)}, 0);
        opm.system_spec.title = "US 4,717,245 Example 2 (Canon EF50mm f/1.0L USM)";
        opm.system_spec.dimensions = "mm";
        opm.radius_mode = true;
        sm.gaps.get(0).thi = 1.0E10d;
        sm.add_surface(new SurfaceData(138.055d, 5.101d).max_aperture(30.275d).rindex(1.60311d, 60.7d));
        sm.add_surface(new SurfaceData(652.512d, 0.099d).max_aperture(30.275d));
        sm.add_surface(new SurfaceData(87.469d, 4.898d).max_aperture(28.02d).rindex(1.6968d, 55.5d));
        sm.add_surface(new SurfaceData(271.835d, 0.151d).max_aperture(28.02d));
        sm.add_surface(new SurfaceData(0.0d, 3.999d).max_aperture(24.465d).rindex(1.51742d, 52.4d));
        sm.ifcs.get(sm.cur_surface).profile = new EvenPolynomial().r(0.0d).cc(0.0d).coefs(new double[]{0.007358d, 4.638E-7d, 1.284E-9d, -1.638E-12d, 1.636E-15d});
        sm.add_surface(new SurfaceData(40.57d, 7.8d).max_aperture(23.255d).rindex(1.883d, 40.8d));
        sm.add_surface(new SurfaceData(145.746d, 1.3d).max_aperture(23.255d));
        sm.add_surface(new SurfaceData(568.62d, 2.699d).max_aperture(22.04d).rindex(1.51742d, 52.4d));
        sm.add_surface(new SurfaceData(26.655d, 8.367d).max_aperture(18.315d));
        sm.add_surface(new SurfaceData(0.0d, 10.229d).max_aperture(17.6665d));
        sm.set_stop();
        sm.add_surface(new SurfaceData(-25.418d, 2.007d).max_aperture(18.14d).rindex(1.84666d, 23.9d));
        sm.add_surface(new SurfaceData(76.965d, 13.26d).max_aperture(21.92d).rindex(1.883d, 40.8d));
        sm.add_surface(new SurfaceData(-36.192d, 1.638d).max_aperture(22.199d));
        sm.add_surface(new SurfaceData(-31.273d, 2.501d).max_aperture(22.199d).rindex(1.80518d, 25.4d));
        sm.add_surface(new SurfaceData(Double.NEGATIVE_INFINITY, 0.151d).max_aperture(24.925d));
        sm.ifcs.get(sm.cur_surface).profile = new EvenPolynomial().r(Double.NEGATIVE_INFINITY).cc(0.0d).coefs(new double[]{-0.007396d, 2.39E-7d, 2.218E-9d, -3.207E-12d, 1.925E-15d});
        sm.add_surface(new SurfaceData(-208.993d, 6.802d).max_aperture(26.98d).rindex(1.883d, 40.8d));
        sm.add_surface(new SurfaceData(-51.62d, 0.099d).max_aperture(26.98d));
        sm.add_surface(new SurfaceData(1947.956d, 6.599d).max_aperture(27.24d).rindex(1.883d, 40.8d));
        sm.add_surface(new SurfaceData(-72.602d, 0.499d).max_aperture(27.24d));
        sm.add_surface(new SurfaceData(74.043d, 4.602d).max_aperture(23.6d).rindex(1.55963d, 61.2d));
        sm.add_surface(new SurfaceData(499.996d, 38.65d).max_aperture(23.6d));
        sm.do_apertures = false;
        opm.update_model();
        VigCalc.set_vig(opm, false);
        opm.update_model();
        return opm;
    }

    @Test
    public void first_order_data() {
        var fod = build().optical_spec.parax_data.fod;
        assertClose("fod.bfl", 126.60238320955598d, fod.bfl, 1.0e-12);
        assertClose("fod.efl", 93.72586557101575d, fod.efl, 1.0e-12);
        assertClose("fod.enp_dist", 31.24637344524322d, fod.enp_dist, 1.0e-12);
        assertClose("fod.enp_radius", 46.86293296799492d, fod.enp_radius, 1.0e-12);
        assertClose("fod.exp_dist", -11.033417082861206d, fod.exp_dist, 1.0e-12);
        assertClose("fod.exp_radius", 112.79409262944039d, fod.exp_radius, 1.0e-12);
        assertClose("fod.ffl", -7.694220456705352d, fod.ffl, 1.0e-12);
        assertClose("fod.fl_img", 93.72586557101575d, fod.fl_img, 1.0e-12);
        assertClose("fod.fl_obj", 93.72586557101575d, fod.fl_obj, 1.0e-12);
        assertClose("fod.fno", 0.9999999999999998d, fod.fno, 1.0e-12);
        assertClose("fod.img_dist", 126.6023840880097d, fod.img_dist, 1.0e-12);
        assertClose("fod.img_ht", 39.01431247595568d, fod.img_ht, 1.0e-12);
        assertClose("fod.img_na", -0.5000000000000001d, fod.img_na, 1.0e-12);
        assertClose("fod.m", -9.372585818567813E-9d, fod.m, 1.0e-12);
        assertClose("fod.n_img", 1.0d, fod.n_img, 1.0e-12);
        assertClose("fod.n_obj", 1.0d, fod.n_obj, 1.0e-12);
        assertClose("fod.obj_ang", 22.600000000000005d, fod.obj_ang, 1.0e-12);
        assertClose("fod.obj_dist", 1.0E10d, fod.obj_dist, 1.0e-12);
        assertClose("fod.obj_na", 4.6862932821565245E-9d, fod.obj_na, 1.0e-12);
        assertClose("fod.opt_inv", 19.507156237977842d, fod.opt_inv, 1.0e-12);
        assertClose("fod.power", 0.010669413335450113d, fod.power, 1.0e-12);
        assertClose("fod.pp1", 86.0316451143104d, fod.pp1, 1.0e-12);
        assertClose("fod.pp_sep", 29.64587252422983d, fod.pp_sep, 1.0e-12);
        assertClose("fod.ppk", 32.876517638540236d, fod.ppk, 1.0e-12);
        assertClose("fod.red", -1.066941332724083E8d, fod.red, 1.0e-12);
    }

    @Test
    public void paraxial_rays() {
        var pd = build().optical_spec.parax_data;
        assertClose("ax.0.aoi", 4.6862932821565245E-9d, pd.ax_ray.get(0).aoi, 1.0e-12);
        assertClose("ax.0.ht", 0.0d, pd.ax_ray.get(0).ht, 1.0e-12);
        assertClose("ax.0.slp", 4.6862932821565245E-9d, pd.ax_ray.get(0).slp, 1.0e-12);
        assertClose("ax.1.aoi", 0.2117454110407466d, pd.ax_ray.get(1).aoi, 1.0e-12);
        assertClose("ax.1.ht", 46.862932821565245d, pd.ax_ray.get(1).ht, 1.0e-12);
        assertClose("ax.1.slp", -0.1277057701664914d, pd.ax_ray.get(1).slp, 1.0e-12);
        assertClose("ax.2.aoi", -0.09119265854717631d, pd.ax_ray.get(2).aoi, 1.0e-12);
        assertClose("ax.2.ht", 46.21150568794597d, pd.ax_ray.get(2).ht, 1.0e-12);
        assertClose("ax.2.slp", -0.1620135870326999d, pd.ax_ray.get(2).slp, 1.0e-12);
        assertClose("ax.3.aoi", 0.21577187089441002d, pd.ax_ray.get(3).aoi, 1.0e-12);
        assertClose("ax.3.ht", 46.19546634282973d, pd.ax_ray.get(3).ht, 1.0e-12);
        assertClose("ax.3.slp", -0.3123634266719248d, pd.ax_ray.get(3).slp, 1.0e-12);
        assertClose("ax.4.aoi", -0.25121517285058687d, pd.ax_ray.get(4).aoi, 1.0e-12);
        assertClose("ax.4.ht", 44.665510278990645d, pd.ax_ray.get(4).ht, 1.0e-12);
        assertClose("ax.4.slp", -0.415526281718064d, pd.ax_ray.get(4).slp, 1.0e-12);
        assertClose("ax.5.aoi", -0.2738373566435555d, pd.ax_ray.get(5).aoi, 1.0e-12);
        assertClose("ax.5.ht", 44.60276581045122d, pd.ax_ray.get(5).ht, 1.0e-12);
        assertClose("ax.5.slp", -0.2738373566435555d, pd.ax_ray.get(5).slp, 1.0e-12);
        assertClose("ax.6.aoi", 0.6435319800412167d, pd.ax_ray.get(6).aoi, 1.0e-12);
        assertClose("ax.6.ht", 43.50769022123364d, pd.ax_ray.get(6).ht, 1.0e-12);
        assertClose("ax.6.slp", -0.42887842718662733d, pd.ax_ray.get(6).slp, 1.0e-12);
        assertClose("ax.7.aoi", -0.28868993274779053d, pd.ax_ray.get(7).aoi, 1.0e-12);
        assertClose("ax.7.ht", 40.162438489177944d, pd.ax_ray.get(7).ht, 1.0e-12);
        assertClose("ax.7.slp", -0.5642545347895477d, pd.ax_ray.get(7).slp, 1.0e-12);
        assertClose("ax.8.aoi", -0.3261543498259266d, pd.ax_ray.get(8).aoi, 1.0e-12);
        assertClose("ax.8.ht", 39.428907593951536d, pd.ax_ray.get(8).ht, 1.0e-12);
        assertClose("ax.8.slp", -0.39549575110261675d, pd.ax_ray.get(8).slp, 1.0e-12);
        assertClose("ax.9.aoi", 1.5837142789395684d, pd.ax_ray.get(9).aoi, 1.0e-12);
        assertClose("ax.9.ht", 38.361464561725576d, pd.ax_ray.get(9).ht, 1.0e-12);
        assertClose("ax.9.slp", 0.14452971462797282d, pd.ax_ray.get(9).slp, 1.0e-12);
        assertClose("ax.10.aoi", 0.14452971462797282d, pd.ax_ray.get(10).aoi, 1.0e-12);
        assertClose("ax.10.ht", 39.570744684017825d, pd.ax_ray.get(10).ht, 1.0e-12);
        assertClose("ax.10.slp", 0.14452971462797282d, pd.ax_ray.get(10).slp, 1.0e-12);
        assertClose("ax.11.aoi", -0.7962665910857458d, pd.ax_ray.get(11).aoi, 1.0e-12);
        assertClose("ax.11.ht", 41.04913913494736d, pd.ax_ray.get(11).ht, 1.0e-12);
        assertClose("ax.11.slp", 0.8186967866366304d, pd.ax_ray.get(11).slp, 1.0e-12);
        assertClose("ax.12.aoi", 1.3468887867814694d, pd.ax_ray.get(12).aoi, 1.0e-12);
        assertClose("ax.12.ht", 42.692263585727076d, pd.ax_ray.get(12).ht, 1.0e-12);
        assertClose("ax.12.slp", 0.7921916700956112d, pd.ax_ray.get(12).slp, 1.0e-12);
        assertClose("ax.13.aoi", -1.2760261572159315d, pd.ax_ray.get(13).aoi, 1.0e-12);
        assertClose("ax.13.ht", 53.19672513119488d, pd.ax_ray.get(13).ht, 1.0e-12);
        assertClose("ax.13.slp", 0.19382146466721628d, pd.ax_ray.get(13).slp, 1.0e-12);
        assertClose("ax.14.aoi", -0.840566395496126d, pd.ax_ray.get(14).aoi, 1.0e-12);
        assertClose("ax.14.ht", 53.51420469031978d, pd.ax_ray.get(14).ht, 1.0e-12);
        assertClose("ax.14.slp", 0.8706287149927872d, pd.ax_ray.get(14).slp, 1.0e-12);
        assertClose("ax.15.aoi", 1.5716415437306794d, pd.ax_ray.get(15).aoi, 1.0e-12);
        assertClose("ax.15.ht", 55.69164710651674d, pd.ax_ray.get(15).ht, 1.0e-12);
        assertClose("ax.15.slp", 1.5716415437306794d, pd.ax_ray.get(15).slp, 1.0e-12);
        assertClose("ax.16.aoi", 0.6925278159366675d, pd.ax_ray.get(16).aoi, 1.0e-12);
        assertClose("ax.16.ht", 55.92896497962007d, pd.ax_ray.get(16).ht, 1.0e-12);
        assertClose("ax.16.slp", 0.960139482258602d, pd.ax_ray.get(16).slp, 1.0e-12);
        assertClose("ax.17.aoi", -0.47047399435972226d, pd.ax_ray.get(17).aoi, 1.0e-12);
        assertClose("ax.17.ht", 62.45983373794308d, pd.ax_ray.get(17).ht, 1.0e-12);
        assertClose("ax.17.slp", 0.7395189102885358d, pd.ax_ray.get(17).slp, 1.0e-12);
        assertClose("ax.18.aoi", 0.40978268104949805d, pd.ax_ray.get(18).aoi, 1.0e-12);
        assertClose("ax.18.ht", 62.53304611006164d, pd.ax_ray.get(18).ht, 1.0e-12);
        assertClose("ax.18.slp", 0.37768080292182904d, pd.ax_ray.get(18).slp, 1.0e-12);
        assertClose("ax.19.aoi", -0.9753199289395785d, pd.ax_ray.get(19).aoi, 1.0e-12);
        assertClose("ax.19.ht", 65.02536172854279d, pd.ax_ray.get(19).ht, 1.0e-12);
        assertClose("ax.19.slp", -0.07967846274659784d, pd.ax_ray.get(19).slp, 1.0e-12);
        assertClose("ax.20.aoi", 0.5116568357810607d, pd.ax_ray.get(20).aoi, 1.0e-12);
        assertClose("ax.20.ht", 64.98560217563224d, pd.ax_ray.get(20).ht, 1.0e-12);
        assertClose("ax.20.slp", -0.3660169777547528d, pd.ax_ray.get(20).slp, 1.0e-12);
        assertClose("ax.21.aoi", -0.37339660308481504d, pd.ax_ray.get(21).aoi, 1.0e-12);
        assertClose("ax.21.ht", 63.301192044004864d, pd.ax_ray.get(21).ht, 1.0e-12);
        assertClose("ax.21.slp", -0.5000000000000001d, pd.ax_ray.get(21).slp, 1.0e-12);
        assertClose("ax.22.aoi", -0.5000000000000001d, pd.ax_ray.get(22).aoi, 1.0e-12);
        assertClose("ax.22.ht", 43.97619204400486d, pd.ax_ray.get(22).ht, 1.0e-12);
        assertClose("ax.22.slp", -0.5000000000000001d, pd.ax_ray.get(22).slp, 1.0e-12);
        assertClose("pr.0.aoi", 0.41625982418343876d, pd.pr_ray.get(0).aoi, 1.0e-12);
        assertClose("pr.0.ht", -4.1625982548409977E9d, pd.pr_ray.get(0).ht, 1.0e-12);
        assertClose("pr.0.slp", 0.41625982418343876d, pd.pr_ray.get(0).slp, 1.0e-12);
        assertClose("pr.1.aoi", 0.20088863299702692d, pd.pr_ray.get(1).aoi, 1.0e-12);
        assertClose("pr.1.ht", -13.006609916687012d, pd.pr_ray.get(1).ht, 1.0e-12);
        assertClose("pr.1.slp", 0.2951018807366018d, pd.pr_ray.get(1).slp, 1.0e-12);
        assertClose("pr.2.aoi", 0.444824067514978d, pd.pr_ray.get(2).aoi, 1.0e-12);
        assertClose("pr.2.ht", -11.501295223049606d, pd.pr_ray.get(2).ht, 1.0e-12);
        assertClose("pr.2.slp", 0.46245024944427526d, pd.pr_ray.get(2).slp, 1.0e-12);
        assertClose("pr.3.aoi", 0.19535814787601188d, pd.pr_ray.get(3).aoi, 1.0e-12);
        assertClose("pr.3.ht", -11.455512648354622d, pd.pr_ray.get(3).ht, 1.0e-12);
        assertClose("pr.3.slp", 0.32632469200427017d, pd.pr_ray.get(3).slp, 1.0e-12);
        assertClose("pr.4.aoi", 0.4921790403377278d, pd.pr_ray.get(4).aoi, 1.0e-12);
        assertClose("pr.4.ht", -9.857174306917706d, pd.pr_ray.get(4).ht, 1.0e-12);
        assertClose("pr.4.slp", 0.5284406486917577d, pd.pr_ray.get(4).slp, 1.0e-12);
        assertClose("pr.5.aoi", 0.34824942909132456d, pd.pr_ray.get(5).aoi, 1.0e-12);
        assertClose("pr.5.ht", -9.77737976896525d, pd.pr_ray.get(5).ht, 1.0e-12);
        assertClose("pr.5.slp", 0.34824942909132456d, pd.pr_ray.get(5).slp, 1.0e-12);
        assertClose("pr.6.aoi", 0.11408956703826162d, pd.pr_ray.get(6).aoi, 1.0e-12);
        assertClose("pr.6.ht", -8.384730302029043d, pd.pr_ray.get(6).ht, 1.0e-12);
        assertClose("pr.6.slp", 0.3207627319884475d, pd.pr_ray.get(6).slp, 1.0e-12);
        assertClose("pr.7.aoi", 0.5279922406303127d, pd.pr_ray.get(7).aoi, 1.0e-12);
        assertClose("pr.7.ht", -5.8827809925191525d, pd.pr_ray.get(7).ht, 1.0e-12);
        assertClose("pr.7.slp", 0.5683554821087694d, pd.pr_ray.get(7).slp, 1.0e-12);
        assertClose("pr.8.aoi", 0.36859219031481727d, pd.pr_ray.get(8).aoi, 1.0e-12);
        assertClose("pr.8.ht", -5.143918865777752d, pd.pr_ray.get(8).ht, 1.0e-12);
        assertClose("pr.8.slp", 0.3776385109960767d, pd.pr_ray.get(8).slp, 1.0e-12);
        assertClose("pr.9.aoi", 0.33822622814472947d, pd.pr_ray.get(9).aoi, 1.0e-12);
        assertClose("pr.9.ht", -4.124672524599341d, pd.pr_ray.get(9).ht, 1.0e-12);
        assertClose("pr.9.slp", 0.4929691478445734d, pd.pr_ray.get(9).slp, 1.0e-12);
        assertClose("pr.10.aoi", 0.4929691478445734d, pd.pr_ray.get(10).aoi, 1.0e-12);
        assertClose("pr.10.ht", 3.3541620503285685E-7d, pd.pr_ray.get(10).ht, 1.0e-12);
        assertClose("pr.10.slp", 0.4929691478445734d, pd.pr_ray.get(10).slp, 1.0e-12);
        assertClose("pr.11.aoi", 0.15952199973262107d, pd.pr_ray.get(11).aoi, 1.0e-12);
        assertClose("pr.11.ht", 5.042581748718346d, pd.pr_ray.get(11).ht, 1.0e-12);
        assertClose("pr.11.slp", 0.3579082515509524d, pd.pr_ray.get(11).slp, 1.0e-12);
        assertClose("pr.12.aoi", 0.424407388721429d, pd.pr_ray.get(12).aoi, 1.0e-12);
        assertClose("pr.12.ht", 5.760903609581108d, pd.pr_ray.get(12).ht, 1.0e-12);
        assertClose("pr.12.slp", 0.34955643556634414d, pd.pr_ray.get(12).slp, 1.0e-12);
        assertClose("pr.13.aoi", 0.11732978467246669d, pd.pr_ray.get(13).aoi, 1.0e-12);
        assertClose("pr.13.ht", 10.396021945190832d, pd.pr_ray.get(13).ht, 1.0e-12);
        assertClose("pr.13.slp", 0.4045761912040436d, pd.pr_ray.get(13).slp, 1.0e-12);
        assertClose("pr.14.aoi", 0.02822847953462304d, pd.pr_ray.get(14).aoi, 1.0e-12);
        assertClose("pr.14.ht", 11.058717746383055d, pd.pr_ray.get(14).ht, 1.0e-12);
        assertClose("pr.14.slp", 0.38184718405235574d, pd.pr_ray.get(14).slp, 1.0e-12);
        assertClose("pr.15.aoi", 0.6893028997076315d, pd.pr_ray.get(15).aoi, 1.0e-12);
        assertClose("pr.15.ht", 12.013717553697996d, pd.pr_ray.get(15).ht, 1.0e-12);
        assertClose("pr.15.slp", 0.6893028997076315d, pd.pr_ray.get(15).slp, 1.0e-12);
        assertClose("pr.16.aoi", 0.3352740533515448d, pd.pr_ray.get(16).aoi, 1.0e-12);
        assertClose("pr.16.ht", 12.117802291553849d, pd.pr_ray.get(16).ht, 1.0e-12);
        assertClose("pr.16.slp", 0.3932559105982174d, pd.pr_ray.get(16).slp, 1.0e-12);
        assertClose("pr.17.aoi", 0.20089009510745032d, pd.pr_ray.get(17).aoi, 1.0e-12);
        assertClose("pr.17.ht", 14.792728995442923d, pd.pr_ray.get(17).ht, 1.0e-12);
        assertClose("pr.17.slp", 0.4874598160575263d, pd.pr_ray.get(17).slp, 1.0e-12);
        assertClose("pr.18.aoi", 0.2629201088149134d, pd.pr_ray.get(18).aoi, 1.0e-12);
        assertClose("pr.18.ht", 14.840987517232618d, pd.pr_ray.get(18).ht, 1.0e-12);
        assertClose("pr.18.slp", 0.25530135997395775d, pd.pr_ray.get(18).slp, 1.0e-12);
        assertClose("pr.19.aoi", 0.052122601543717784d, pd.pr_ray.get(19).aoi, 1.0e-12);
        assertClose("pr.19.ht", 16.525721191700764d, pd.pr_ray.get(19).ht, 1.0e-12);
        assertClose("pr.19.slp", 0.2797433446596204d, pd.pr_ray.get(19).slp, 1.0e-12);
        assertClose("pr.20.aoi", 0.32367900799059235d, pd.pr_ray.get(20).aoi, 1.0e-12);
        assertClose("pr.20.ht", 16.665313120685916d, pd.pr_ray.get(20).ht, 1.0e-12);
        assertClose("pr.20.slp", 0.09860286141784524d, pd.pr_ray.get(20).slp, 1.0e-12);
        assertClose("pr.21.aoi", 0.20718328031119287d, pd.pr_ray.get(21).aoi, 1.0e-12);
        assertClose("pr.21.ht", 17.11908348893084d, pd.pr_ray.get(21).ht, 1.0e-12);
        assertClose("pr.21.slp", 0.1729448394258041d, pd.pr_ray.get(21).slp, 1.0e-12);
        assertClose("pr.22.aoi", 0.1729448394258041d, pd.pr_ray.get(22).aoi, 1.0e-12);
        assertClose("pr.22.ht", 23.80340153273817d, pd.pr_ray.get(22).ht, 1.0e-12);
        assertClose("pr.22.slp", 0.1729448394258041d, pd.pr_ray.get(22).slp, 1.0e-12);
    }

    @Test
    public void vignetting_factors() {
        var fields = build().optical_spec.fov.fields;
        assertClose("fld.0.vlx", 0.44519567918995484d, fields[0].vlx, 1.0e-6);
        assertClose("fld.0.vly", 0.44519567918995484d, fields[0].vly, 1.0e-6);
        assertClose("fld.0.vux", 0.44519567918995484d, fields[0].vux, 1.0e-6);
        assertClose("fld.0.vuy", 0.44519567918995484d, fields[0].vuy, 1.0e-6);
        assertClose("fld.1.vlx", 0.5499866071753976d, fields[1].vlx, 1.0e-6);
        assertClose("fld.1.vly", 0.49793159406530396d, fields[1].vly, 1.0e-6);
        assertClose("fld.1.vux", 0.5499866071753976d, fields[1].vux, 1.0e-6);
        assertClose("fld.1.vuy", 0.784683572551858d, fields[1].vuy, 1.0e-6);
        assertClose("fld.2.vlx", 0.3975544086228877d, fields[2].vlx, 1.0e-6);
        assertClose("fld.2.vly", 0.5151874958382119d, fields[2].vly, 1.0e-6);
        assertClose("fld.2.vux", 0.3975544086228877d, fields[2].vux, 1.0e-6);
        assertClose("fld.2.vuy", 0.46812037849713106d, fields[2].vuy, 1.0e-6);
    }

    @Test
    public void chief_ray_aiming() {
        var fields = build().optical_spec.fov.fields;
        Assertions.assertNotNull(fields[0].aim_info, "aim.0.x - expected paraxial aiming");
        assertClose("aim.0.x", 0.0d, fields[0].aim_info[0], 1.0e-6);
        Assertions.assertNotNull(fields[0].aim_info, "aim.0.y - expected paraxial aiming");
        assertClose("aim.0.y", 0.0d, fields[0].aim_info[1], 1.0e-6);
        Assertions.assertNotNull(fields[1].aim_info, "aim.1.x - expected paraxial aiming");
        assertClose("aim.1.x", 0.0d, fields[1].aim_info[0], 1.0e-6);
        Assertions.assertNotNull(fields[1].aim_info, "aim.1.y - expected paraxial aiming");
        assertClose("aim.1.y", 1.9768691222235995d, fields[1].aim_info[1], 1.0e-6);
        Assertions.assertNotNull(fields[2].aim_info, "aim.2.x - expected paraxial aiming");
        assertClose("aim.2.x", 0.0d, fields[2].aim_info[0], 1.0e-6);
        Assertions.assertNotNull(fields[2].aim_info, "aim.2.y - expected paraxial aiming");
        assertClose("aim.2.y", 4.052503157247234d, fields[2].aim_info[1], 1.0e-6);
    }

    @Test
    public void seidel_coefficients() {
        var opm = build();
        var third_order = ThirdOrder.compute_third_order(opm);
        double[] sum = new double[5];
        for (ThirdOrderData d : third_order.values()) {
            accumulate(sum, d.seidel());
            if (d.has_aspheric())
                accumulate(sum, d.aspheric());
        }
        var s1 = third_order.get(1).seidel();
        assertClose("seidel.1 S-I", 0.43016131187801093d, s1[0], 1.0e-12);
        assertClose("seidel.1 S-II", 0.4081057411664636d, s1[1], 1.0e-12);
        assertClose("seidel.1 S-III", 0.38718102110554375d, s1[2], 1.0e-12);
        assertClose("seidel.1 S-IV", 1.0369766818836121d, s1[3], 1.0e-12);
        assertClose("seidel.1 S-V", 1.3511371638208634d, s1[4], 1.0e-12);
        var s2 = third_order.get(2).seidel();
        assertClose("seidel.2 S-I", 0.03164796017352968d, s2[0], 1.0e-12);
        assertClose("seidel.2 S-II", -0.15437398796372084d, s2[1], 1.0e-12);
        assertClose("seidel.2 S-III", 0.7530130861247584d, s2[2], 1.0e-12);
        assertClose("seidel.2 S-IV", -0.21939798167304522d, s2[3], 1.0e-12);
        assertClose("seidel.2 S-V", -2.6028941916069477d, s2[4], 1.0e-12);
        var s3 = third_order.get(3).seidel();
        assertClose("seidel.3 S-I", 0.13670147600909738d, s3[0], 1.0e-12);
        assertClose("seidel.3 S-II", 0.12376843679555917d, s3[1], 1.0e-12);
        assertClose("seidel.3 S-III", 0.11205896522870668d, s3[2], 1.0e-12);
        assertClose("seidel.3 S-IV", 1.7865338519059382d, s3[3], 1.0e-12);
        assertClose("seidel.3 S-V", 1.7189709427306674d, s3[4], 1.0e-12);
        var s4 = third_order.get(4).seidel();
        assertClose("seidel.4 S-I", 0.6523730512195085d, s4[0], 1.0e-12);
        assertClose("seidel.4 S-II", -1.2781247989442968d, s4[1], 1.0e-12);
        assertClose("seidel.4 S-III", 2.5040933230191462d, s4[2], 1.0e-12);
        assertClose("seidel.4 S-IV", -0.5748572828824857d, s4[3], 1.0e-12);
        assertClose("seidel.4 S-V", -3.7797459924292207d, s4[4], 1.0e-12);
        var s5 = third_order.get(5).seidel();
        assertClose("seidel.5 S-I", -1.8102750485540409d, s5[0], 1.0e-12);
        assertClose("seidel.5 S-II", 2.3021959453757788d, s5[1], 1.0e-12);
        assertClose("seidel.5 S-III", -2.9277905449440627d, s5[2], 1.0e-12);
        assertClose("seidel.5 S-IV", 0.0d, s5[3], 1.0e-12);
        assertClose("seidel.5 S-V", 3.723383099636502d, s5[4], 1.0e-12);
        var asp5 = third_order.get(5).aspheric();
        assertClose("seidel.5.asp S-I", 7.59820668958418d, asp5[0], 1.0e-12);
        assertClose("seidel.5.asp S-II", -1.665604161922829d, asp5[1], 1.0e-12);
        assertClose("seidel.5.asp S-III", 0.36511736749905027d, asp5[2], 1.0e-12);
        assertClose("seidel.5.asp S-IV", 0.0d, asp5[3], 1.0e-12);
        assertClose("seidel.5.asp S-V", -0.08003743932504241d, asp5[4], 1.0e-12);
        var s6 = third_order.get(6).seidel();
        assertClose("seidel.6 S-I", 3.021874156360615d, s6[0], 1.0e-12);
        assertClose("seidel.6 S-II", 0.535737655370621d, s6[1], 1.0e-12);
        assertClose("seidel.6 S-III", 0.09497908269207202d, s6[2], 1.0e-12);
        assertClose("seidel.6 S-IV", 1.2000773018852358d, s6[3], 1.0e-12);
        assertClose("seidel.6 S-V", 0.2295960834721815d, s6[4], 1.0e-12);
        var s7 = third_order.get(7).seidel();
        assertClose("seidel.7 S-I", 1.1263076050805245d, s7[0], 1.0e-12);
        assertClose("seidel.7 S-II", -2.0599321576099494d, s7[1], 1.0e-12);
        assertClose("seidel.7 S-III", 3.76746145974235d, s7[2], 1.0e-12);
        assertClose("seidel.7 S-IV", -1.2243389442165622d, s7[3], 1.0e-12);
        assertClose("seidel.7 S-V", -4.651180394097531d, s7[4], 1.0e-12);
        var s8 = third_order.get(8).seidel();
        assertClose("seidel.8 S-I", -2.9322405479845566d, s8[0], 1.0e-12);
        assertClose("seidel.8 S-II", 3.3137714296571152d, s8[1], 1.0e-12);
        assertClose("seidel.8 S-III", -3.7449455146370876d, s8[2], 1.0e-12);
        assertClose("seidel.8 S-IV", 0.22819346422268494d, s8[3], 1.0e-12);
        assertClose("seidel.8 S-V", 3.9743371251930126d, s8[4], 1.0e-12);
        var s9 = third_order.get(9).seidel();
        assertClose("seidel.9 S-I", -38.98365651536096d, s9[0], 1.0e-12);
        assertClose("seidel.9 S-II", -8.325551696931674d, s9[1], 1.0e-12);
        assertClose("seidel.9 S-III", -1.7780479630218717d, s9[2], 1.0e-12);
        assertClose("seidel.9 S-IV", -4.867956016743691d, s9[3], 1.0e-12);
        assertClose("seidel.9 S-V", -1.4193550492050224d, s9[4], 1.0e-12);
        var s10 = third_order.get(10).seidel();
        assertClose("seidel.10 S-I", -0.0d, s10[0], 1.0e-12);
        assertClose("seidel.10 S-II", -0.0d, s10[1], 1.0e-12);
        assertClose("seidel.10 S-III", -0.0d, s10[2], 1.0e-12);
        assertClose("seidel.10 S-IV", -0.0d, s10[3], 1.0e-12);
        assertClose("seidel.10 S-V", -0.0d, s10[4], 1.0e-12);
        var s11 = third_order.get(11).seidel();
        assertClose("seidel.11 S-I", -26.52096496699591d, s11[0], 1.0e-12);
        assertClose("seidel.11 S-II", 5.313141872002006d, s11[1], 1.0e-12);
        assertClose("seidel.11 S-III", -1.0644211697105d, s11[2], 1.0e-12);
        assertClose("seidel.11 S-IV", -6.863863677597635d, s11[3], 1.0e-12);
        assertClose("seidel.11 S-V", 1.5883321835315318d, s11[4], 1.0e-12);
        var s12 = third_order.get(12).seidel();
        assertClose("seidel.12 S-I", 6.214930940789312d, s12[0], 1.0e-12);
        assertClose("seidel.12 S-II", 1.958337345704225d, s12[1], 1.0e-12);
        assertClose("seidel.12 S-III", 0.6170760698899742d, s12[2], 1.0e-12);
        assertClose("seidel.12 S-IV", 0.0516704580862784d, s12[3], 1.0e-12);
        assertClose("seidel.12 S-V", 0.21072338743953986d, s12[4], 1.0e-12);
        var s13 = third_order.get(13).seidel();
        assertClose("seidel.13 S-I", 19.652203656601174d, s13[0], 1.0e-12);
        assertClose("seidel.13 S-II", -1.8070074898772537d, s13[1], 1.0e-12);
        assertClose("seidel.13 S-III", 0.16615317679021133d, s13[2], 1.0e-12);
        assertClose("seidel.13 S-IV", 4.930440532819051d, s13[3], 1.0e-12);
        assertClose("seidel.13 S-V", -0.46862851449393245d, s13[4], 1.0e-12);
        var s14 = third_order.get(14).seidel();
        assertClose("seidel.14 S-I", -35.54345558000632d, s14[0], 1.0e-12);
        assertClose("seidel.14 S-II", 1.1936448016551904d, s14[1], 1.0e-12);
        assertClose("seidel.14 S-III", -0.040085801711410456d, s14[2], 1.0e-12);
        assertClose("seidel.14 S-IV", -5.427387692632636d, s14[3], 1.0e-12);
        assertClose("seidel.14 S-V", 0.18361245996527123d, s14[4], 1.0e-12);
        var s15 = third_order.get(15).seidel();
        assertClose("seidel.15 S-I", -149.8522434608856d, s15[0], 1.0e-12);
        assertClose("seidel.15 S-II", -65.72337461892842d, s15[1], 1.0e-12);
        assertClose("seidel.15 S-III", -28.82547415733215d, s15[2], 1.0e-12);
        assertClose("seidel.15 S-IV", 0.0d, s15[3], 1.0e-12);
        assertClose("seidel.15 S-V", -12.642502993991444d, s15[4], 1.0e-12);
        var asp15 = third_order.get(15).aspheric();
        assertClose("seidel.15.asp S-I", -14.809524582014445d, asp15[0], 1.0e-12);
        assertClose("seidel.15.asp S-II", -3.1946881566023935d, asp15[1], 1.0e-12);
        assertClose("seidel.15.asp S-III", -0.6891532784469261d, asp15[2], 1.0e-12);
        assertClose("seidel.15.asp S-IV", 0.0d, asp15[3], 1.0e-12);
        assertClose("seidel.15.asp S-V", -0.1486630988419368d, asp15[4], 1.0e-12);
        var s16 = third_order.get(16).seidel();
        assertClose("seidel.16 S-I", 100.97902164182294d, s16[0], 1.0e-12);
        assertClose("seidel.16 S-II", 48.88705566798992d, s16[1], 1.0e-12);
        assertClose("seidel.16 S-III", 23.667729920798635d, s16[2], 1.0e-12);
        assertClose("seidel.16 S-IV", -0.8538204808954706d, s16[3], 1.0e-12);
        assertClose("seidel.16 S-V", 11.044916485218707d, s16[4], 1.0e-12);
        var s17 = third_order.get(17).seidel();
        assertClose("seidel.17 S-I", -3.174548366545776d, s17[0], 1.0e-12);
        assertClose("seidel.17 S-II", 1.355516629875556d, s17[1], 1.0e-12);
        assertClose("seidel.17 S-III", -0.5787989728657013d, s17[2], 1.0e-12);
        assertClose("seidel.17 S-IV", 3.4568481937967284d, s17[3], 1.0e-12);
        assertClose("seidel.17 S-V", -1.2289129444946312d, s17[4], 1.0e-12);
        var s18 = third_order.get(18).seidel();
        assertClose("seidel.18 S-I", 20.066046543411442d, s18[0], 1.0e-12);
        assertClose("seidel.18 S-II", 12.874548839319024d, s18[1], 1.0e-12);
        assertClose("seidel.18 S-III", 8.260421775530821d, s18[2], 1.0e-12);
        assertClose("seidel.18 S-IV", 0.09160499711686872d, s18[3], 1.0e-12);
        assertClose("seidel.18 S-V", 5.35873254151596d, s18[4], 1.0e-12);
        var s19 = third_order.get(19).seidel();
        assertClose("seidel.19 S-I", 17.335101107205094d, s19[0], 1.0e-12);
        assertClose("seidel.19 S-II", -0.9264145445211008d, s19[1], 1.0e-12);
        assertClose("seidel.19 S-III", 0.0495090223583133d, s19[2], 1.0e-12);
        assertClose("seidel.19 S-IV", 2.4578180182885747d, s19[3], 1.0e-12);
        assertClose("seidel.19 S-V", -0.13399542488741958d, s19[4], 1.0e-12);
        var s20 = third_order.get(20).seidel();
        assertClose("seidel.20 S-I", 6.414447891671871d, s20[0], 1.0e-12);
        assertClose("seidel.20 S-II", 4.057841086427151d, s20[1], 1.0e-12);
        assertClose("seidel.20 S-III", 2.5670290819689767d, s20[2], 1.0e-12);
        assertClose("seidel.20 S-IV", 1.8440951480831955d, s20[3], 1.0e-12);
        assertClose("seidel.20 S-V", 2.790519377557004d, s20[4], 1.0e-12);
        var s21 = third_order.get(21).seidel();
        assertClose("seidel.21 S-I", 2.3416363116465506d, s21[0], 1.0e-12);
        assertClose("seidel.21 S-II", -1.2992830902442256d, s21[1], 1.0e-12);
        assertClose("seidel.21 S-III", 0.7209217504009197d, s21[2], 1.0e-12);
        assertClose("seidel.21 S-IV", -0.2730868587939185d, s21[3], 1.0e-12);
        assertClose("seidel.21 S-V", -0.24848619702057298d, s21[4], 1.0e-12);
        assertClose("seidel.sum S-I", -87.62624872489373d, sum[0], 1.0e-12);
        assertClose("seidel.sum S-II", -4.11068925220726d, sum[1], 1.0e-12);
        assertClose("seidel.sum S-III", 4.384027700479769d, sum[2], 1.0e-12);
        assertClose("seidel.sum S-IV", -3.2204502873472767d, sum[3], 1.0e-12);
        assertClose("seidel.sum S-V", 4.76985860968754d, sum[4], 1.0e-12);
    }

    private static void accumulate(double[] into, double[] add) {
        for (int i = 0; i < into.length; i++)
            into[i] += add[i];
    }

}

