package org.redukti.rayoptics.upstream;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.redukti.rayoptics.elem.profiles.EvenPolynomial;
import org.redukti.rayoptics.elem.profiles.RadialPolynomial;
import org.redukti.rayoptics.optical.OpticalModel;
import org.redukti.rayoptics.parax.ThirdOrder;
import org.redukti.rayoptics.parax.ThirdOrderData;
import org.redukti.rayoptics.raytr.Trace;
import org.redukti.rayoptics.raytr.VigCalc;
import org.redukti.rayoptics.seq.SurfaceData;
import org.redukti.rayoptics.specs.FieldSpec;
import org.redukti.rayoptics.specs.ImageKey;
import org.redukti.rayoptics.specs.PupilSpec;
import org.redukti.rayoptics.specs.ValueKey;
import org.redukti.rayoptics.specs.WvlSpec;
import org.redukti.rayoptics.specs.WvlWt;
import org.redukti.rayoptics.util.Pair;

/**
 * Upstream regression test for US004123144_Example08P.txt.
 * <p>
 * Generated by JavaTestWriter - do not edit, regenerate.
 * Reference values were captured from upstream ray-optics running the
 * equivalent generated Python model.
 */
public class US004123144Example08PUpstreamTest {

    /** Relative tolerance, floored so near-zero values do not demand exactness. */
    private static void assertClose(String what, double expected, double actual, double rel) {
        double tol = Math.max(rel, Math.abs(expected) * rel);
        Assertions.assertEquals(expected, actual, tol, what);
    }

    private static OpticalModel build() {
        var opm = new OpticalModel();
        var sm = opm.seq_model;
        var osp = opm.optical_spec;
        osp.pupil = new PupilSpec(osp, new Pair<>(ImageKey.Image, ValueKey.Fnum), 2.0d);
        osp.fov = new FieldSpec(osp, new Pair<>(ImageKey.Object, ValueKey.Angle), 22.5d, new double[]{0.0d, 0.707d, 1.0d}, true, false);
        osp.wvls = new WvlSpec(new WvlWt[]{new WvlWt(587.5618d, 1.0d)}, 0);
        opm.system_spec.title = "US 4,123,144 Example 8 (Leica Summicron R 50mm f/2)";
        opm.system_spec.dimensions = "mm";
        opm.radius_mode = true;
        sm.gaps.get(0).thi = 1.0E10d;
        sm.add_surface(new SurfaceData(42.71d, 3.99d).max_aperture(14.47d).rindex(1.7343d, 28.19d));
        sm.add_surface(new SurfaceData(195.38d, 0.2d).max_aperture(13.53d));
        sm.add_surface(new SurfaceData(20.5d, 7.18d).max_aperture(12.01d).rindex(1.67133d, 41.64d));
        sm.add_surface(new SurfaceData(0.0d, 1.29d).max_aperture(10.745d).rindex(1.7919d, 25.55d));
        sm.add_surface(new SurfaceData(14.94d, 5.35d).max_aperture(9.195d));
        sm.add_surface(new SurfaceData(0.0d, 7.61d).max_aperture(9.0295d));
        sm.set_stop();
        sm.add_surface(new SurfaceData(-14.94d, 1.0d).max_aperture(8.75d).rindex(1.65222d, 33.6d));
        sm.add_surface(new SurfaceData(0.0d, 5.22d).max_aperture(9.635d).rindex(1.79227d, 47.15d));
        sm.add_surface(new SurfaceData(-20.5d, 0.2d).max_aperture(10.19d));
        sm.add_surface(new SurfaceData(0.0d, 3.69d).max_aperture(11.48d).rindex(1.79227d, 47.15d));
        sm.add_surface(new SurfaceData(-42.71d, 37.32d).max_aperture(11.985d));
        sm.do_apertures = false;
        opm.update_model();
        VigCalc.set_vig(opm, false);
        opm.update_model();
        return opm;
    }

    @Test
    public void first_order_data() {
        var fod = build().optical_spec.parax_data.fod;
        assertClose("fod.bfl", 37.356135262147404d, fod.bfl, 1.0e-12);
        assertClose("fod.efl", 52.01602328738747d, fod.efl, 1.0e-12);
        assertClose("fod.enp_dist", 20.2096230285742d, fod.enp_dist, 1.0e-12);
        assertClose("fod.enp_radius", 13.004005879190803d, fod.enp_radius, 1.0e-12);
        assertClose("fod.exp_dist", -23.96470179806542d, fod.exp_dist, 1.0e-12);
        assertClose("fod.exp_radius", 15.339243215873386d, fod.exp_radius, 1.0e-12);
        assertClose("fod.ffl", -23.887511564176897d, fod.ffl, 1.0e-12);
        assertClose("fod.fl_img", 52.01602328738747d, fod.fl_img, 1.0e-12);
        assertClose("fod.fl_obj", 52.01602328738747d, fod.fl_obj, 1.0e-12);
        assertClose("fod.fno", 2.0000000000000004d, fod.fno, 1.0e-12);
        assertClose("fod.img_dist", 37.356135532714056d, fod.img_dist, 1.0e-12);
        assertClose("fod.img_ht", 21.54574240136118d, fod.img_ht, 1.0e-12);
        assertClose("fod.img_na", -0.24999999999999997d, fod.img_na, 1.0e-12);
        assertClose("fod.m", -5.2016020379852534E-9d, fod.m, 1.0e-12);
        assertClose("fod.n_img", 1.0d, fod.n_img, 1.0e-12);
        assertClose("fod.n_obj", 1.0d, fod.n_obj, 1.0e-12);
        assertClose("fod.obj_ang", 22.5d, fod.obj_ang, 1.0e-12);
        assertClose("fod.obj_dist", 1.0E10d, fod.obj_dist, 1.0e-12);
        assertClose("fod.obj_na", 1.30040058529102E-9d, fod.obj_na, 1.0e-12);
        assertClose("fod.opt_inv", 5.3864356003402944d, fod.opt_inv, 1.0e-12);
        assertClose("fod.power", 0.019224845284212144d, fod.power, 1.0e-12);
        assertClose("fod.pp1", 28.128511723210572d, fod.pp1, 1.0e-12);
        assertClose("fod.pp_sep", -7.05839974845064d, fod.pp_sep, 1.0e-12);
        assertClose("fod.ppk", -14.659888025240065d, fod.ppk, 1.0e-12);
        assertClose("fod.red", -1.9224845238288775E8d, fod.red, 1.0e-12);
    }

    @Test
    public void paraxial_rays() {
        var pd = build().optical_spec.parax_data;
        assertClose("ax.0.aoi", 1.30040058529102E-9d, pd.ax_ray.get(0).aoi, 1.0e-12);
        assertClose("ax.0.ht", 0.0d, pd.ax_ray.get(0).ht, 1.0e-12);
        assertClose("ax.0.slp", 1.30040058529102E-9d, pd.ax_ray.get(0).slp, 1.0e-12);
        assertClose("ax.1.aoi", 0.17555910681132314d, pd.ax_ray.get(1).aoi, 1.0e-12);
        assertClose("ax.1.ht", 13.004005852910199d, pd.ax_ray.get(1).ht, 1.0e-12);
        assertClose("ax.1.slp", -0.128913050831154d, pd.ax_ray.get(1).slp, 1.0e-12);
        assertClose("ax.2.aoi", -0.11270898710736178d, pd.ax_ray.get(2).aoi, 1.0e-12);
        assertClose("ax.2.ht", 12.489642780093893d, pd.ax_ray.get(2).ht, 1.0e-12);
        assertClose("ax.2.slp", -0.17663386570339973d, pd.ax_ray.get(2).slp, 1.0e-12);
        assertClose("ax.3.aoi", 0.25781488059921087d, pd.ax_ray.get(3).aoi, 1.0e-12);
        assertClose("ax.3.ht", 12.454316006953214d, pd.ax_ray.get(3).ht, 1.0e-12);
        assertClose("ax.3.slp", -0.3497127294960679d, pd.ax_ray.get(3).slp, 1.0e-12);
        assertClose("ax.4.aoi", -0.32618191650687156d, pd.ax_ray.get(4).aoi, 1.0e-12);
        assertClose("ax.4.ht", 9.943378609171447d, pd.ax_ray.get(4).ht, 1.0e-12);
        assertClose("ax.4.slp", -0.32618191650687156d, pd.ax_ray.get(4).slp, 1.0e-12);
        assertClose("ax.5.aoi", 0.5576534453970757d, pd.ax_ray.get(5).aoi, 1.0e-12);
        assertClose("ax.5.ht", 9.522603936877582d, pd.ax_ray.get(5).ht, 1.0e-12);
        assertClose("ax.5.slp", -0.07973637634841169d, pd.ax_ray.get(5).slp, 1.0e-12);
        assertClose("ax.6.aoi", -0.07973637634841169d, pd.ax_ray.get(6).aoi, 1.0e-12);
        assertClose("ax.6.ht", 9.096014323413579d, pd.ax_ray.get(6).ht, 1.0e-12);
        assertClose("ax.6.slp", -0.07973637634841169d, pd.ax_ray.get(6).slp, 1.0e-12);
        assertClose("ax.7.aoi", -0.3921737379463598d, pd.ax_ray.get(7).aoi, 1.0e-12);
        assertClose("ax.7.ht", 8.489220499402165d, pd.ax_ray.get(7).ht, 1.0e-12);
        assertClose("ax.7.slp", 0.17604717901496314d, pd.ax_ray.get(7).slp, 1.0e-12);
        assertClose("ax.8.aoi", 0.16229065381449356d, pd.ax_ray.get(8).aoi, 1.0e-12);
        assertClose("ax.8.ht", 8.665267678417129d, pd.ax_ray.get(8).ht, 1.0e-12);
        assertClose("ax.8.slp", 0.16229065381449356d, pd.ax_ray.get(8).slp, 1.0e-12);
        assertClose("ax.9.aoi", -0.540781757204085d, pd.ax_ray.get(9).aoi, 1.0e-12);
        assertClose("ax.9.ht", 9.512424891328784d, pd.ax_ray.get(9).ht, 1.0e-12);
        assertClose("ax.9.slp", -0.07676103079780283d, pd.ax_ray.get(9).slp, 1.0e-12);
        assertClose("ax.10.aoi", -0.0428289436289191d, pd.ax_ray.get(10).aoi, 1.0e-12);
        assertClose("ax.10.ht", 9.497072685169224d, pd.ax_ray.get(10).ht, 1.0e-12);
        assertClose("ax.10.slp", -0.0428289436289191d, pd.ax_ray.get(10).slp, 1.0e-12);
        assertClose("ax.11.aoi", -0.4686615285220911d, pd.ax_ray.get(11).aoi, 1.0e-12);
        assertClose("ax.11.ht", 9.339033883178512d, pd.ax_ray.get(11).ht, 1.0e-12);
        assertClose("ax.11.slp", -0.24999999999999997d, pd.ax_ray.get(11).slp, 1.0e-12);
        assertClose("ax.12.aoi", -0.24999999999999997d, pd.ax_ray.get(12).aoi, 1.0e-12);
        assertClose("ax.12.ht", 0.009033883178513946d, pd.ax_ray.get(12).ht, 1.0e-12);
        assertClose("ax.12.slp", -0.24999999999999997d, pd.ax_ray.get(12).slp, 1.0e-12);
        assertClose("pr.0.aoi", 0.41421356237309503d, pd.pr_ray.get(0).aoi, 1.0e-12);
        assertClose("pr.0.ht", -4.1421356321020503E9d, pd.pr_ray.get(0).ht, 1.0e-12);
        assertClose("pr.0.slp", 0.41421356237309503d, pd.pr_ray.get(0).slp, 1.0e-12);
        assertClose("pr.1.aoi", 0.12582308043196636d, pd.pr_ray.get(1).aoi, 1.0e-12);
        assertClose("pr.1.ht", -8.371099948883057d, pd.pr_ray.get(1).ht, 1.0e-12);
        assertClose("pr.1.slp", 0.3218216744119021d, pd.pr_ray.get(1).slp, 1.0e-12);
        assertClose("pr.2.aoi", 0.4952269530520369d, pd.pr_ray.get(2).aoi, 1.0e-12);
        assertClose("pr.2.ht", -7.087031467979568d, pd.pr_ray.get(2).ht, 1.0e-12);
        assertClose("pr.2.slp", 0.5315000181967783d, pd.pr_ray.get(2).slp, 1.0e-12);
        assertClose("pr.3.aoi", 0.11426620244440178d, pd.pr_ray.get(3).aoi, 1.0e-12);
        assertClose("pr.3.ht", -6.980731464340212d, pd.pr_ray.get(3).ht, 1.0e-12);
        assertClose("pr.3.slp", 0.45478968850977797d, pd.pr_ray.get(3).slp, 1.0e-12);
        assertClose("pr.4.aoi", 0.424188654554968d, pd.pr_ray.get(4).aoi, 1.0e-12);
        assertClose("pr.4.ht", -3.7153415008400064d, pd.pr_ray.get(4).ht, 1.0e-12);
        assertClose("pr.4.slp", 0.424188654554968d, pd.pr_ray.get(4).slp, 1.0e-12);
        assertClose("pr.5.aoi", 0.3801179254163231d, pd.pr_ray.get(5).aoi, 1.0e-12);
        assertClose("pr.5.ht", -3.1681381364640977d, pd.pr_ray.get(5).ht, 1.0e-12);
        assertClose("pr.5.slp", 0.5921753642693417d, pd.pr_ray.get(5).slp, 1.0e-12);
        assertClose("pr.6.aoi", 0.5921753642693417d, pd.pr_ray.get(6).aoi, 1.0e-12);
        assertClose("pr.6.ht", 6.237688010557463E-8d, pd.pr_ray.get(6).ht, 1.0e-12);
        assertClose("pr.6.slp", 0.5921753642693417d, pd.pr_ray.get(6).slp, 1.0e-12);
        assertClose("pr.7.aoi", 0.17584735157912623d, pd.pr_ray.get(7).aoi, 1.0e-12);
        assertClose("pr.7.ht", 4.506454584466571d, pd.pr_ray.get(7).ht, 1.0e-12);
        assertClose("pr.7.slp", 0.47748420462240404d, pd.pr_ray.get(7).slp, 1.0e-12);
        assertClose("pr.8.aoi", 0.4401730501326409d, pd.pr_ray.get(8).aoi, 1.0e-12);
        assertClose("pr.8.ht", 4.983938789088975d, pd.pr_ray.get(8).ht, 1.0e-12);
        assertClose("pr.8.slp", 0.4401730501326409d, pd.pr_ray.get(8).slp, 1.0e-12);
        assertClose("pr.9.aoi", 0.15229096690805222d, pd.pr_ray.get(9).aoi, 1.0e-12);
        assertClose("pr.9.ht", 7.281642110781361d, pd.pr_ray.get(9).ht, 1.0e-12);
        assertClose("pr.9.slp", 0.5074930210925088d, pd.pr_ray.get(9).slp, 1.0e-12);
        assertClose("pr.10.aoi", 0.2831565674214872d, pd.pr_ray.get(10).aoi, 1.0e-12);
        assertClose("pr.10.ht", 7.383140714999863d, pd.pr_ray.get(10).ht, 1.0e-12);
        assertClose("pr.10.slp", 0.2831565674214872d, pd.pr_ray.get(10).slp, 1.0e-12);
        assertClose("pr.11.aoi", 0.15382336861992263d, pd.pr_ray.get(11).aoi, 1.0e-12);
        assertClose("pr.11.ht", 8.42798844878515d, pd.pr_ray.get(11).ht, 1.0e-12);
        assertClose("pr.11.slp", 0.35115393403282713d, pd.pr_ray.get(11).slp, 1.0e-12);
        assertClose("pr.12.aoi", 0.35115393403282713d, pd.pr_ray.get(12).aoi, 1.0e-12);
        assertClose("pr.12.ht", 21.53305326689026d, pd.pr_ray.get(12).ht, 1.0e-12);
        assertClose("pr.12.slp", 0.35115393403282713d, pd.pr_ray.get(12).slp, 1.0e-12);
    }

    @Test
    public void vignetting_factors() {
        var fields = build().optical_spec.fov.fields;
        assertClose("fld.0.vlx", 3.2688951932380306E-4d, fields[0].vlx, 1.0e-6);
        assertClose("fld.0.vly", 3.2688951932380306E-4d, fields[0].vly, 1.0e-6);
        assertClose("fld.0.vux", 3.2688951932380306E-4d, fields[0].vux, 1.0e-6);
        assertClose("fld.0.vuy", 3.2688951932380306E-4d, fields[0].vuy, 1.0e-6);
        assertClose("fld.1.vlx", 0.08340828086149987d, fields[1].vlx, 1.0e-6);
        assertClose("fld.1.vly", 0.28315399334910485d, fields[1].vly, 1.0e-6);
        assertClose("fld.1.vux", 0.08340828086149987d, fields[1].vux, 1.0e-6);
        assertClose("fld.1.vuy", 0.3998404511153971d, fields[1].vuy, 1.0e-6);
        assertClose("fld.2.vlx", 0.2860660474792589d, fields[2].vlx, 1.0e-6);
        assertClose("fld.2.vly", 0.40768998138030577d, fields[2].vly, 1.0e-6);
        assertClose("fld.2.vux", 0.2860660474792589d, fields[2].vux, 1.0e-6);
        assertClose("fld.2.vuy", 0.7340026500159416d, fields[2].vuy, 1.0e-6);
    }

    @Test
    public void chief_ray_aiming() {
        var fields = build().optical_spec.fov.fields;
        Assertions.assertNotNull(fields[0].aim_info, "aim.0.x - expected paraxial aiming");
        assertClose("aim.0.x", 0.0d, fields[0].aim_info[0], 1.0e-6);
        Assertions.assertNotNull(fields[0].aim_info, "aim.0.y - expected paraxial aiming");
        assertClose("aim.0.y", 0.0d, fields[0].aim_info[1], 1.0e-6);
        Assertions.assertNotNull(fields[1].aim_info, "aim.1.x - expected paraxial aiming");
        assertClose("aim.1.x", 0.0d, fields[1].aim_info[0], 1.0e-6);
        Assertions.assertNotNull(fields[1].aim_info, "aim.1.y - expected paraxial aiming");
        assertClose("aim.1.y", 0.223792575288455d, fields[1].aim_info[1], 1.0e-6);
        Assertions.assertNotNull(fields[2].aim_info, "aim.2.x - expected paraxial aiming");
        assertClose("aim.2.x", 0.0d, fields[2].aim_info[0], 1.0e-6);
        Assertions.assertNotNull(fields[2].aim_info, "aim.2.y - expected paraxial aiming");
        assertClose("aim.2.y", 0.7466467371853281d, fields[2].aim_info[1], 1.0e-6);
    }

    @Test
    public void seidel_coefficients() {
        var opm = build();
        var third_order = ThirdOrder.compute_third_order(opm);
        double[] sum = new double[5];
        for (ThirdOrderData d : third_order.values()) {
            accumulate(sum, d.seidel());
            if (d.has_aspheric())
                accumulate(sum, d.aspheric());
        }
        var s1 = third_order.get(1).seidel();
        assertClose("seidel.1 S-I", 0.08960763179853773d, s1[0], 1.0e-12);
        assertClose("seidel.1 S-II", 0.06422172263169801d, s1[1], 1.0e-12);
        assertClose("seidel.1 S-III", 0.04602766053516054d, s1[2], 1.0e-12);
        assertClose("seidel.1 S-IV", 0.2876223804761453d, s1[3], 1.0e-12);
        assertClose("seidel.1 S-V", 0.2391267346296771d, s1[4], 1.0e-12);
        var s2 = third_order.get(2).seidel();
        assertClose("seidel.2 S-I", 0.01623128704128753d, s2[0], 1.0e-12);
        assertClose("seidel.2 S-II", -0.07131792265964572d, s2[1], 1.0e-12);
        assertClose("seidel.2 S-III", 0.3133606151840777d, s2[2], 1.0e-12);
        assertClose("seidel.2 S-IV", -0.06287415226807333d, s2[3], 1.0e-12);
        assertClose("seidel.2 S-V", -1.1006012119735613d, s2[4], 1.0e-12);
        var s3 = third_order.get(3).seidel();
        assertClose("seidel.3 S-I", 0.07540299252596552d, s3[0], 1.0e-12);
        assertClose("seidel.3 S-II", 0.03341938056042551d, s3[1], 1.0e-12);
        assertClose("seidel.3 S-III", 0.014811812630088255d, s3[2], 1.0e-12);
        assertClose("seidel.3 S-IV", 0.5684901300309484d, s3[3], 1.0e-12);
        assertClose("seidel.3 S-V", 0.25852541060239664d, s3[4], 1.0e-12);
        var s4 = third_order.get(4).seidel();
        assertClose("seidel.4 S-I", -0.09243225840205095d, s4[0], 1.0e-12);
        assertClose("seidel.4 S-II", 0.12020505535357331d, s4[1], 1.0e-12);
        assertClose("seidel.4 S-III", -0.15632264733493756d, s4[2], 1.0e-12);
        assertClose("seidel.4 S-IV", 0.0d, s4[3], 1.0e-12);
        assertClose("seidel.4 S-V", 0.2032923656823295d, s4[4], 1.0e-12);
        var s5 = third_order.get(5).seidel();
        assertClose("seidel.5 S-I", -0.3029274680026439d, s5[0], 1.0e-12);
        assertClose("seidel.5 S-II", -0.20648695285437293d, s5[1], 1.0e-12);
        assertClose("seidel.5 S-III", -0.1407494077054508d, s5[2], 1.0e-12);
        assertClose("seidel.5 S-IV", -0.858240331702018d, s5[3], 1.0e-12);
        assertClose("seidel.5 S-V", -0.6809496299002897d, s5[4], 1.0e-12);
        var s6 = third_order.get(6).seidel();
        assertClose("seidel.6 S-I", -0.0d, s6[0], 1.0e-12);
        assertClose("seidel.6 S-II", 0.0d, s6[1], 1.0e-12);
        assertClose("seidel.6 S-III", -0.0d, s6[2], 1.0e-12);
        assertClose("seidel.6 S-IV", -0.0d, s6[3], 1.0e-12);
        assertClose("seidel.6 S-V", -0.0d, s6[4], 1.0e-12);
        var s7 = third_order.get(7).seidel();
        assertClose("seidel.7 S-I", -0.663966399209073d, s7[0], 1.0e-12);
        assertClose("seidel.7 S-II", 0.2977168574567171d, s7[1], 1.0e-12);
        assertClose("seidel.7 S-III", -0.13349369383674684d, s7[2], 1.0e-12);
        assertClose("seidel.7 S-IV", -0.7666172430100713d, s7[3], 1.0e-12);
        assertClose("seidel.7 S-V", 0.4036020494405679d, s7[4], 1.0e-12);
        var s8 = third_order.get(8).seidel();
        assertClose("seidel.8 S-I", 0.011731086566439161d, s8[0], 1.0e-12);
        assertClose("seidel.8 S-II", 0.03181765575497622d, s8[1], 1.0e-12);
        assertClose("seidel.8 S-III", 0.08629748080100161d, s8[2], 1.0e-12);
        assertClose("seidel.8 S-IV", 0.0d, s8[3], 1.0e-12);
        assertClose("seidel.8 S-V", 0.23406046158615898d, s8[4], 1.0e-12);
        var s9 = third_order.get(9).seidel();
        assertClose("seidel.9 S-I", 0.4654368423186554d, s9[0], 1.0e-12);
        assertClose("seidel.9 S-II", -0.13107288810518927d, s9[1], 1.0e-12);
        assertClose("seidel.9 S-III", 0.03691177928814095d, s9[2], 1.0e-12);
        assertClose("seidel.9 S-IV", 0.6256318623967786d, s9[3], 1.0e-12);
        assertClose("seidel.9 S-V", -0.18658065008080532d, s9[4], 1.0e-12);
        var s10 = third_order.get(10).seidel();
        assertClose("seidel.10 S-I", -0.0029582570417442393d, s10[0], 1.0e-12);
        assertClose("seidel.10 S-II", 0.01955803338855039d, s10[1], 1.0e-12);
        assertClose("seidel.10 S-III", -0.12930474418886648d, s10[2], 1.0e-12);
        assertClose("seidel.10 S-IV", 0.0d, s10[3], 1.0e-12);
        assertClose("seidel.10 S-V", 0.8548772025072936d, s10[4], 1.0e-12);
        var s11 = third_order.get(11).seidel();
        assertClose("seidel.11 S-I", 0.4637969459046185d, s11[0], 1.0e-12);
        assertClose("seidel.11 S-II", -0.15222672276868482d, s11[1], 1.0e-12);
        assertClose("seidel.11 S-III", 0.04996362164415726d, s11[2], 1.0e-12);
        assertClose("seidel.11 S-IV", 0.300291575254834d, s11[3], 1.0e-12);
        assertClose("seidel.11 S-V", -0.11496022392436994d, s11[4], 1.0e-12);
        assertClose("seidel.sum S-I", 0.05992240349999184d, sum[0], 1.0e-12);
        assertClose("seidel.sum S-II", 0.005834218758047821d, sum[1], 1.0e-12);
        assertClose("seidel.sum S-III", -0.012497522983375357d, sum[2], 1.0e-12);
        assertClose("seidel.sum S-IV", 0.0943042211785437d, sum[3], 1.0e-12);
        assertClose("seidel.sum S-V", 0.11039250856939736d, sum[4], 1.0e-12);
    }

    private static void accumulate(double[] into, double[] add) {
        for (int i = 0; i < into.length; i++)
            into[i] += add[i];
    }

}

