package org.redukti.rayoptics.integration;

import org.redukti.rayoptics.optical.OpticalModel;
import org.redukti.rayoptics.raytr.VigCalc;
import org.redukti.rayoptics.seq.SurfaceData;
import org.redukti.rayoptics.specs.FieldSpec;
import org.redukti.rayoptics.specs.ImageKey;
import org.redukti.rayoptics.specs.PupilSpec;
import org.redukti.rayoptics.specs.ValueKey;
import org.redukti.rayoptics.specs.WvlSpec;
import org.redukti.rayoptics.specs.WvlWt;
import org.redukti.rayoptics.util.Pair;

/** Generated by JavaModelWriter. Do not edit - regenerate instead. */
public final class US003549241Example05 {

    private US003549241Example05() {}

    public static OpticalModel build() {
        var opm = new OpticalModel();
        var sm = opm.seq_model;
        var osp = opm.optical_spec;
        osp.pupil = new PupilSpec(osp, new Pair<>(ImageKey.Image, ValueKey.Fnum), 4.0d);
        osp.fov = new FieldSpec(osp, new Pair<>(ImageKey.Object, ValueKey.Angle), 45.0d,
                new double[]{0.0d, 0.707d, 1.0d}, true, true);
        osp.wvls = new WvlSpec(new WvlWt[]{
                new WvlWt(587.5618d, 1.0d),
                new WvlWt(486.1327d, 1.0d),
                new WvlWt(656.2725d, 1.0d)}, 0);
        opm.system_spec.title = "US 3,549,241 Example 5";
        opm.system_spec.dimensions = "mm";
        opm.radius_mode = true;
        sm.gaps.get(0).thi = 1.0E10d;
        sm.add_surface(new SurfaceData(44.14d, 1.76d).max_aperture(27.78d).rindex(1.7552d, 27.5d, "J-SF4", "Hikari"));
        sm.add_surface(new SurfaceData(32.869d, 9.392d).max_aperture(23.9d).rindex(1.6968d, 55.6d, "J-LAK14", "Hikari"));
        sm.add_surface(new SurfaceData(98.608d, 0.117d).max_aperture(23.9d));
        sm.add_surface(new SurfaceData(32.283d, 0.94d).max_aperture(16.81d).rindex(1.6516d, 58.5d, "J-LAK7", "Hikari"));
        sm.add_surface(new SurfaceData(13.852d, 5.869d).max_aperture(11.185d));
        sm.add_surface(new SurfaceData(26.06d, 0.94d).max_aperture(12.42d).rindex(1.6968d, 55.6d, "J-LAK14", "Hikari"));
        sm.add_surface(new SurfaceData(9.86d, 4.696d).max_aperture(7.81d));
        sm.add_surface(new SurfaceData(193.696d, 1.173d).max_aperture(7.925d).rindex(1.74443d, 49.4d, "N-LAK28", "Schott"));
        sm.add_surface(new SurfaceData(12.679d, 12.56d).max_aperture(6.35d).rindex(1.58065d, 37.1d, "J-LF5", "Hikari"));
        sm.add_surface(new SurfaceData(-44.842d, 0.117d).max_aperture(4.94d));
        sm.add_surface(new SurfaceData(28.644d, 2.7d).max_aperture(5.56d).rindex(1.62004d, 36.3d, "J-F2", "Hikari"));
        sm.add_surface(new SurfaceData(-14.083d, 0.94d).max_aperture(5.56d).rindex(1.62041d, 60.3d, "J-SK16", "Hikari"));
        sm.add_surface(new SurfaceData(0.0d, 0.467d).max_aperture(5.56d));
        sm.add_surface(new SurfaceData(0.0d, 1.646d).max_aperture(5.1015d));
        sm.set_stop();
        sm.add_surface(new SurfaceData(0.0d, 1.76d).max_aperture(5.9d).rindex(1.62004d, 36.3d, "J-F2", "Hikari"));
        sm.add_surface(new SurfaceData(-18.606d, 0.469d).max_aperture(5.9d));
        sm.add_surface(new SurfaceData(-15.144d, 0.821d).max_aperture(5.955d).rindex(1.80518d, 25.5d, "J-SF6", "Hikari"));
        sm.add_surface(new SurfaceData(21.224d, 1.173d).max_aperture(5.39d).rindex(1.62041d, 38.0d, "J-SK16", "Hikari"));
        sm.add_surface(new SurfaceData(53.765d, 0.821d).max_aperture(5.39d));
        sm.add_surface(new SurfaceData(-62.217d, 1.76d).max_aperture(6.235d).rindex(1.5168d, 64.2d, "J-BK7A", "Hikari"));
        sm.add_surface(new SurfaceData(-15.612d, 0.117d).max_aperture(6.235d));
        sm.add_surface(new SurfaceData(-211.304d, 2.376d).max_aperture(7.195d).rindex(1.56384d, 60.8d, "J-SK11", "Hikari"));
        sm.add_surface(new SurfaceData(-15.075d, 44.97d).max_aperture(7.195d));
        sm.do_apertures = false;
        opm.update_model();
        VigCalc.set_pupil(opm);
        opm.update_model();
        return opm;
    }
}
