package org.redukti.examples;

import org.redukti.importers.obench.OpticalBenchDataImporter;
import org.redukti.optim.*;
import org.redukti.rayoptics.seq.Glass;
import org.redukti.spec.Prescription;

public class ZeissOtusML50mm {

    private static Prescription getPrescription(String specfile, boolean weighted) throws Exception {
        OpticalBenchDataImporter.LensSpecifications specs = new OpticalBenchDataImporter.LensSpecifications();
        specs.parse_file(specfile);
        return Prescription.build_prescription(specs,true,true,false);
    }

    public static void main(String[] args) throws Exception {
        boolean weighted = true;
        var prescription = getPrescription(args[0], weighted);
        //prescription._generate_d_line_only = false;
        var analysis = new Analysis(prescription, new double[]{0.0,0.3,0.7,1.0}, new int[] {10,20,40});
        final int SAGITTAL = 0;
        final int TANGENTIAL = 1;

        final double WT_d = weighted ? Prescription.WT_d : 1.0;
        final double WT_e = weighted ? Prescription.WT_e : 1.0;
        final double WT_C = weighted ? Prescription.WT_C : 1.0;
        final double WT_F = weighted ? Prescription.WT_F : 1.0;
        final double WT_g = weighted ? Prescription.WT_g : 1.0;

        var f = new LMDerMeritFunction(analysis,
                new Var[]{
                        new VarRadius(prescription, 0),
                        new VarRadius(prescription, 1),
                        new VarRadius(prescription, 2),
                        new VarRadius(prescription, 3),
                        new VarRadius(prescription, 4),
                        new VarRadius(prescription, 5),
                        new VarRadius(prescription, 6),
                        new VarRadius(prescription, 8),
                        new VarRadius(prescription, 9),
                        //  new VarRadius(prescription, 10), // asph
                        new VarAsphCoeff(prescription, 10, 1, 1E6),
                        new VarAsphCoeff(prescription, 10, 2, 1E9),
                        new VarAsphCoeff(prescription, 10, 3, 1E12),
                        new VarAsphCoeff(prescription, 10, 4, 1E15),
                        new VarAsphCoeff(prescription, 10, 5, 1E18),
                        new VarAsphCoeff(prescription, 10, 6, 1E22),
                        new VarAsphCoeff(prescription, 10, 7, 1E24),

                        new VarRadius(prescription, 11),
                        new VarRadius(prescription, 12),
                        new VarRadius(prescription, 13),
                        new VarRadius(prescription, 14),
//                        new VarRadius(prescription, 15),  // stop
                        new VarRadius(prescription, 16),
                        new VarRadius(prescription, 17),
                        new VarRadius(prescription, 18),
                        new VarRadius(prescription, 19),
                        new VarRadius(prescription, 20),
                        new VarRadius(prescription, 21),
                        new VarRadius(prescription, 22),
                        new VarRadius(prescription, 23),
                        // 24,25 are aspherical
                        new VarAsphCoeff(prescription, 24, 1, 1E5),
                        new VarAsphCoeff(prescription, 25, 2, 1E7),
                        new VarAsphCoeff(prescription, 24, 3, 1E9),
                        new VarAsphCoeff(prescription, 24, 4, 1E11),
                        new VarAsphCoeff(prescription, 24, 5, 1E14),
                        new VarAsphCoeff(prescription, 24, 6, 1E18),
                        new VarAsphCoeff(prescription, 24, 7, 1E20),
                        new VarAsphCoeff(prescription, 24, 8, 1E23),

                        new VarAsphCoeff(prescription, 25, 1, 1E5),
                        new VarAsphCoeff(prescription, 25, 2, 1E7),
                        new VarAsphCoeff(prescription, 25, 3, 1E9),
                        new VarAsphCoeff(prescription, 25, 4, 1E11),
                        new VarAsphCoeff(prescription, 25, 5, 1E14),
                        new VarAsphCoeff(prescription, 25, 6, 1E17),
                        new VarAsphCoeff(prescription, 25, 7, 1E21),
                        new VarThickness(prescription, 25)

                },
                // xy=0 sagittal
                new Goal[] {
                        new GeoMTF(analysis,1,SAGITTAL,10,0.9,1.0),
                        new GeoMTF(analysis,1,TANGENTIAL,10,0.9,1.0),
                        new GeoMTF(analysis,2,SAGITTAL,10,0.93,1.0),
                        new GeoMTF(analysis,2,TANGENTIAL,10,0.93,1.0),
                        new GeoMTF(analysis,3,SAGITTAL,10,0.94,1.0),
                        new GeoMTF(analysis,3,TANGENTIAL,10,0.90,1.0),
                        new GeoMTF(analysis,4,SAGITTAL,10,0.93,1.0),
                        new GeoMTF(analysis,4,TANGENTIAL,10,0.82,1.0),
                        // below are figures from patent
                        new GeoMTF(analysis,1,SAGITTAL,20,0.82,1.0),
                        new GeoMTF(analysis,1,TANGENTIAL,20,0.82,1.0),
                        new GeoMTF(analysis,2,SAGITTAL,20,0.85,1.0),
                        new GeoMTF(analysis,2,TANGENTIAL,20,0.85,1.0),
                        new GeoMTF(analysis,3,SAGITTAL,20,0.85,1.0),
                        new GeoMTF(analysis,3,TANGENTIAL,20,0.78,1.0),
                        new GeoMTF(analysis,4,SAGITTAL,20,0.80,1.0),
                        new GeoMTF(analysis,4,TANGENTIAL,20,0.62,1.0),

                        new GeoMTF(analysis,1,SAGITTAL,40,0.62,1.0),
                        new GeoMTF(analysis,1,TANGENTIAL,40,0.62,1.0),
                        new GeoMTF(analysis,2,SAGITTAL,40,0.65,1.0),
                        new GeoMTF(analysis,2,TANGENTIAL,40,0.62,1.0),
                        new GeoMTF(analysis,3,SAGITTAL,40,0.64,1.0),
                        new GeoMTF(analysis,3,TANGENTIAL,40,0.45,1.0),
                        new GeoMTF(analysis,4,SAGITTAL,40,0.58,1.0),
                        new GeoMTF(analysis,4,TANGENTIAL,40,0.38,1.0),

                      new GoalParax(analysis, ParaxHelper.Effective_focal_length,50.15, 1.0),
                      new GoalParax(analysis, ParaxHelper.Fno, 1.435, 1.0),

                        new GoalRayAberration(analysis,1,SAGITTAL,0,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,1,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,2,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,3,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,4,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,5,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,6,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,7,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,8,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,9,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,SAGITTAL,0, Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,1,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,2,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,3,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,4,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,5,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,6,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,7,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,8,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,9,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,SAGITTAL,0,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,1,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,2,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,3,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,4,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,5,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,6,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,7,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,8,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,9,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,SAGITTAL,0,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,1,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,2,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,3,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,4,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,5,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,6,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,7,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,8,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,SAGITTAL,9,Glass.C, 0,WT_C),

                        new GoalRayAberration(analysis,2,SAGITTAL,0,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,1,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,2,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,3,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,4,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,5,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,6,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,7,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,8,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,SAGITTAL,9,Glass.e, 0,WT_e),

                        new GoalRayAberration(analysis,2,SAGITTAL,0,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,1,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,2,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,3,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,4,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,5,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,6,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,7,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,8,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,SAGITTAL,9,Glass.d, 0,WT_d),

                        new GoalRayAberration(analysis,2,SAGITTAL,0,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,1,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,2,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,3,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,4,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,5,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,6,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,7,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,8,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,9,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,SAGITTAL,0,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,1,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,2,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,3,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,4,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,5,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,6,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,7,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,8,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,SAGITTAL,9,Glass.C, 0,WT_C),

                        new GoalRayAberration(analysis,3,SAGITTAL,0,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,1,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,2,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,3,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,4,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,5,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,6,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,7,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,8,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,SAGITTAL,9,Glass.e, 0,WT_e),

                        new GoalRayAberration(analysis,3,SAGITTAL,0,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,1,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,2,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,3,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,4,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,5,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,6,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,7,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,8,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,SAGITTAL,9,Glass.d, 0,WT_d),

                        new GoalRayAberration(analysis,3,SAGITTAL,0,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,1,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,2,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,3,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,4,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,5,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,6,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,7,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,8,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,9,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,SAGITTAL,0,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,1,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,2,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,3,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,4,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,5,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,6,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,7,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,8,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,SAGITTAL,9,Glass.C, 0,WT_C),

                        new GoalRayAberration(analysis,4,SAGITTAL,0,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,1,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,2,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,3,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,4,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,5,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,6,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,7,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,8,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,SAGITTAL,9,Glass.d, 0,WT_d),

                        new GoalRayAberration(analysis,4,SAGITTAL,0,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,1,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,2,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,3,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,4,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,5,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,6,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,7,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,8,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,9,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,SAGITTAL,0,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,1,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,2,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,3,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,4,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,5,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,6,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,7,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,8,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,SAGITTAL,9,Glass.C, 0,WT_C),

                        // tangential
                        new GoalRayAberration(analysis,1,TANGENTIAL,0,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,1,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,2,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,3,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,4,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,5,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,6,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,7,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,8,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,9,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,1,TANGENTIAL,0, Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,1,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,2,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,3,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,4,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,5,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,6,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,7,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,8,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,9,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,1,TANGENTIAL,0,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,1,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,2,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,3,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,4,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,5,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,6,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,7,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,8,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,9,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,1,TANGENTIAL,0,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,1,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,2,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,3,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,4,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,5,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,6,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,7,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,8,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,1,TANGENTIAL,9,Glass.C, 0,WT_C),

                        new GoalRayAberration(analysis,2,TANGENTIAL,0,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,1,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,2,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,3,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,4,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,5,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,6,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,7,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,8,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,2,TANGENTIAL,9,Glass.e, 0,WT_e),

                        new GoalRayAberration(analysis,2,TANGENTIAL,0,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,1,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,2,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,3,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,4,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,5,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,6,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,7,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,8,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,2,TANGENTIAL,9,Glass.d, 0,WT_d),

                        new GoalRayAberration(analysis,2,TANGENTIAL,0,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,1,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,2,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,3,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,4,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,5,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,6,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,7,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,8,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,9,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,2,TANGENTIAL,0,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,1,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,2,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,3,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,4,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,5,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,6,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,7,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,8,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,2,TANGENTIAL,9,Glass.C, 0,WT_C),

                        new GoalRayAberration(analysis,3,TANGENTIAL,0,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,1,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,2,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,3,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,4,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,5,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,6,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,7,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,8,Glass.e, 0,WT_e),
                        new GoalRayAberration(analysis,3,TANGENTIAL,9,Glass.e, 0,WT_e),

                        new GoalRayAberration(analysis,3,TANGENTIAL,0,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,1,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,2,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,3,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,4,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,5,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,6,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,7,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,8,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,3,TANGENTIAL,9,Glass.d, 0,WT_d),

                        new GoalRayAberration(analysis,3,TANGENTIAL,0,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,1,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,2,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,3,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,4,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,5,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,6,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,7,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,8,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,9,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,3,TANGENTIAL,0,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,1,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,2,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,3,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,4,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,5,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,6,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,7,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,8,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,3,TANGENTIAL,9,Glass.C, 0,WT_C),

                        new GoalRayAberration(analysis,4,TANGENTIAL,0,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,1,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,2,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,3,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,4,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,5,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,6,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,7,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,8,Glass.d, 0,WT_d),
                        new GoalRayAberration(analysis,4,TANGENTIAL,9,Glass.d, 0,WT_d),

                        new GoalRayAberration(analysis,4,TANGENTIAL,0,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,1,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,2,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,3,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,4,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,5,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,6,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,7,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,8,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,9,Glass.F, 0,WT_F),
                        new GoalRayAberration(analysis,4,TANGENTIAL,0,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,1,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,2,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,3,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,4,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,5,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,6,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,7,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,8,Glass.C, 0,WT_C),
                        new GoalRayAberration(analysis,4,TANGENTIAL,9,Glass.C, 0,WT_C),

                },
                false);
        analysis.compute();
        var lm = f.getSolver();
        System.out.println("Aberrations:\n");
        System.out.println(analysis._ray_aberrations.list_ray_fans());
        System.out.println("Before:\n");
        System.out.println(f.toString());
        var istatus = lm.solve();
        System.out.println("Status = " + istatus);
        System.out.println("After:\n");
        System.out.println(f.toString());
        System.out.println(prescription.toString());
    }
}
