package org.redukti.exporters;

import org.redukti.exporters.ModelSpec.Op;
import org.redukti.spec.SurfaceType;
import org.redukti.spec.VigType;

/**
 * Renders a {@link ModelSpec} as a Java class that builds the same OpticalModel,
 * so the Python and Java sides of a comparison are known to describe the same
 * system.
 * <p>
 * The generated class is deliberately declarative - it only builds and returns
 * the model. Whatever dumps results for comparison is hand written and lives
 * outside the generated code, so the dump format is defined once rather than
 * regenerated per lens.
 *
 * @see PythonModelWriter for the sibling that must stay in step with this one
 */
public class JavaModelWriter {

    private final String package_name;
    private final String class_name;

    public JavaModelWriter(String package_name, String class_name) {
        this.package_name = package_name;
        this.class_name = class_name;
    }

    public String write(ModelSpec spec) {
        StringBuilder sb = new StringBuilder();
        preamble(sb);
        for (Op op : spec.ops())
            emit(op, spec, sb);
        sb.append("        return opm;\n")
          .append("    }\n")
          .append("}\n");
        return sb.toString();
    }

    private void preamble(StringBuilder sb) {
        sb.append("package ").append(package_name).append(";\n\n")
          .append("import org.redukti.rayoptics.elem.profiles.EvenPolynomial;\n")
          .append("import org.redukti.rayoptics.elem.profiles.RadialPolynomial;\n")
          .append("import org.redukti.rayoptics.optical.OpticalModel;\n")
          .append("import org.redukti.rayoptics.raytr.Trace;\n")
          .append("import org.redukti.rayoptics.raytr.VigCalc;\n")
          .append("import org.redukti.rayoptics.seq.SurfaceData;\n")
          .append("import org.redukti.rayoptics.specs.FieldSpec;\n")
          .append("import org.redukti.rayoptics.specs.ImageKey;\n")
          .append("import org.redukti.rayoptics.specs.PupilSpec;\n")
          .append("import org.redukti.rayoptics.specs.ValueKey;\n")
          .append("import org.redukti.rayoptics.specs.WvlSpec;\n")
          .append("import org.redukti.rayoptics.specs.WvlWt;\n")
          .append("import org.redukti.rayoptics.util.Pair;\n\n")
          .append("/** Generated by ").append(JavaModelWriter.class.getSimpleName())
          .append(". Do not edit - regenerate instead. */\n")
          .append("public final class ").append(class_name).append(" {\n\n")
          .append("    private ").append(class_name).append("() {}\n\n")
          .append("    public static OpticalModel build() {\n")
          .append("        var opm = new OpticalModel();\n")
          .append("        var sm = opm.seq_model;\n")
          .append("        var osp = opm.optical_spec;\n");
    }

    private void emit(Op op, ModelSpec spec, StringBuilder sb) {
        if (op instanceof ModelSpec.SetPupil) {
            sb.append("        osp.pupil = new PupilSpec(osp, new Pair<>(ImageKey.Image, ValueKey.Fnum), ")
              .append(num(spec.fno())).append(");\n");
        }
        else if (op instanceof ModelSpec.SetFieldSpec) {
            sb.append("        osp.fov = new FieldSpec(osp, new Pair<>(ImageKey.Object, ValueKey.Angle), ")
              .append(num(spec.half_angle_degrees())).append(", ").append(array(spec.fields()))
              .append(", ").append(spec.is_relative()).append(", ").append(spec.is_wide_angle()).append(");\n");
        }
        else if (op instanceof ModelSpec.SetSpectralRegion) {
            double[] wvls = spec.wavelengths();
            double[] wts = spec.weights();
            sb.append("        osp.wvls = new WvlSpec(new WvlWt[]{");
            for (int i = 0; i < wvls.length; i++) {
                if (i > 0) sb.append(", ");
                sb.append("new WvlWt(").append(num(wvls[i])).append(", ").append(num(wts[i])).append(")");
            }
            sb.append("}, ").append(spec.reference_wavelength_index()).append(");\n");
        }
        else if (op instanceof ModelSpec.SetTitle) {
            sb.append("        opm.system_spec.title = \"").append(escape(spec.title())).append("\";\n")
              .append("        opm.system_spec.dimensions = \"").append(escape(spec.dimensions())).append("\";\n");
        }
        else if (op instanceof ModelSpec.SetRadiusMode) {
            sb.append("        opm.radius_mode = ").append(spec.radius_mode()).append(";\n");
        }
        else if (op instanceof ModelSpec.SetObjectDistance) {
            sb.append("        sm.gaps.get(0).thi = ").append(num(spec.object_distance())).append(";\n");
        }
        else if (op instanceof ModelSpec.AddSurface o) {
            SurfaceType s = o.surface();
            sb.append("        sm.add_surface(new SurfaceData(").append(num(s.get_radius_of_curvature()))
              .append(", ").append(num(spec.thickness(s))).append(")")
              .append(".max_aperture(").append(num(spec.semi_diameter(s))).append(")");
            if (s.get_refractive_index() != 0.0) {
                if (s.get_glass_name() != null && s.get_catalog_name() != null) {
                    sb.append(".rindex(").append(num(s.get_refractive_index()))
                      .append(", ").append(num(s.get_abbe_vd()))
                      .append(", \"").append(escape(s.get_glass_name())).append("\", \"")
                      .append(escape(s.get_catalog_name())).append("\")");
                }
                else {
                    sb.append(".rindex(").append(num(s.get_refractive_index()))
                      .append(", ").append(num(s.get_abbe_vd())).append(")");
                }
            }
            sb.append(");\n");
        }
        else if (op instanceof ModelSpec.SetProfile o) {
            SurfaceType s = o.surface();
            sb.append("        sm.ifcs.get(sm.cur_surface).profile = new ")
              .append(s.is_odd_asphere() ? "RadialPolynomial" : "EvenPolynomial")
              .append("().r(").append(num(s.get_radius_of_curvature()))
              .append(").cc(").append(num(s.get_cc()))
              .append(").coefs(").append(array(s.get_aspheric_coeffs())).append(");\n");
        }
        else if (op instanceof ModelSpec.SetStop) {
            sb.append("        sm.set_stop();\n");
        }
        else if (op instanceof ModelSpec.SetDoApertures) {
            sb.append("        sm.do_apertures = ").append(spec.do_apertures()).append(";\n");
        }
        else if (op instanceof ModelSpec.UpdateModel) {
            sb.append("        opm.update_model();\n");
        }
        else if (op instanceof ModelSpec.ApplyVignetting) {
            sb.append("        ").append(vignetting(spec.vig_type())).append("\n");
        }
        else {
            throw new IllegalStateException("No Java rendering for op " + op.getClass().getSimpleName());
        }
    }

    private String vignetting(VigType kind) {
        return switch (kind) {
            case Paraxial -> "Trace.apply_paraxial_vignetting(opm);";
            case SetVig -> "VigCalc.set_vig(opm, false);";
            case SetPupil -> "VigCalc.set_pupil(opm);";
            case SetStopAperture -> "VigCalc.set_stop_aperture(opm);";
            case SetApertures -> "VigCalc.set_vig(opm, false); VigCalc.set_ape(opm);";
            case SetFnum -> "VigCalc.set_stop_aperture(opm); VigCalc.set_ape(opm);";
            case None -> throw new IllegalStateException("VigType.None should not be emitted");
        };
    }

    /**
     * Rendered the same way as the Python side: shortest round tripping decimal.
     * Java needs a trailing d so that values outside int range, and any future
     * integral valued literal, stay double typed.
     * <p>
     * Double.toString spells the non-finite values Infinity, -Infinity and NaN,
     * which are not Java literals - a plane surface recorded as an infinite
     * radius would emit source that does not compile.
     */
    static String num(double value) {
        if (Double.isNaN(value))
            return "Double.NaN";
        if (Double.isInfinite(value))
            return value > 0 ? "Double.POSITIVE_INFINITY" : "Double.NEGATIVE_INFINITY";
        return Double.toString(value) + "d";
    }

    static String array(double[] values) {
        StringBuilder sb = new StringBuilder("new double[]{");
        for (int i = 0; i < values.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(num(values[i]));
        }
        return sb.append("}").toString();
    }

    static String escape(String value) {
        return value == null ? "" : value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
