package org.redukti.exporters;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.TreeMap;

/**
 * Emits a JUnit regression test that builds a model and asserts it against
 * reference values captured from upstream ray-optics.
 * <p>
 * The model half comes from {@link JavaModelWriter}, so the system under test is
 * the same one the Python side described. The reference values are inlined as
 * literals rather than loaded from a fixture at run time: when a change moves a
 * number, the diff names the quantity and shows the delta, which is how the
 * ZeissOtus regeneration stayed reviewable.
 * <p>
 * Regenerate rather than edit. Values are grouped into separate test methods so
 * a failure says which layer moved - first order, paraxial, vignetting or Seidel
 * - instead of stopping at the first bad assertion.
 */
public class JavaTestWriter {

    /** Relative tolerance for quantities that are analytic on both sides. */
    private static final String EXACT_TOL = "1.0e-12";
    /**
     * Vignetting factors come from an iterated search - SecantSolver here
     * against scipy's newton upstream - so they agree to about 1e-8 rather than
     * to the last bit. Compare them as converging to the same root.
     */
    private static final String SOLVER_TOL = "1.0e-6";

    private final String package_name;
    private final String class_name;
    private final String source_description;

    public JavaTestWriter(String package_name, String class_name, String source_description) {
        this.package_name = package_name;
        this.class_name = class_name;
        this.source_description = source_description;
    }

    public String write(ModelSpec spec, Map<String, String> reference) {
        var sb = new StringBuilder();
        preamble(sb);
        model(spec, sb);
        first_order(reference, sb);
        paraxial(reference, sb);
        vignetting(reference, sb);
        chief_ray_aiming(reference, sb);
        aberration_fans(reference, sb);
        seidel(reference, sb);
        sb.append("}\n");
        return sb.toString();
    }

    private void preamble(StringBuilder sb) {
        sb.append("package ").append(package_name).append(";\n\n")
          .append("import org.junit.jupiter.api.Assertions;\n")
          .append("import org.junit.jupiter.api.Test;\n")
          .append("import org.redukti.rayoptics.elem.profiles.EvenPolynomial;\n")
          .append("import org.redukti.rayoptics.elem.profiles.RadialPolynomial;\n")
          .append("import org.redukti.rayoptics.analysis.TransverseRayAberrationAnalysis;\n")
          .append("import org.redukti.rayoptics.analysis.WavefrontAberrationAnalysis;\n")
          .append("import org.redukti.rayoptics.optical.OpticalModel;\n")
          .append("import org.redukti.rayoptics.parax.ThirdOrder;\n")
          .append("import org.redukti.rayoptics.parax.ThirdOrderData;\n")
          .append("import org.redukti.rayoptics.raytr.Trace;\n")
          .append("import org.redukti.rayoptics.raytr.TraceOptions;\n")
          .append("import org.redukti.rayoptics.raytr.VigCalc;\n")
          .append("import org.redukti.rayoptics.seq.SurfaceData;\n")
          .append("import org.redukti.rayoptics.specs.FieldSpec;\n")
          .append("import org.redukti.rayoptics.specs.ImageKey;\n")
          .append("import org.redukti.rayoptics.specs.PupilSpec;\n")
          .append("import org.redukti.rayoptics.specs.ValueKey;\n")
          .append("import org.redukti.rayoptics.specs.WvlSpec;\n")
          .append("import org.redukti.rayoptics.specs.WvlWt;\n")
          .append("import org.redukti.rayoptics.util.Pair;\n\n")
          .append("/**\n")
          .append(" * Upstream regression test for ").append(source_description).append(".\n")
          .append(" * <p>\n")
          .append(" * Generated by ").append(JavaTestWriter.class.getSimpleName())
          .append(" - do not edit, regenerate.\n")
          .append(" * Reference values were captured from upstream ray-optics running the\n")
          .append(" * equivalent generated Python model.\n")
          .append(" */\n")
          .append("public class ").append(class_name).append(" {\n\n")
          .append("    /** Relative tolerance, floored so near-zero values do not demand exactness. */\n")
          .append("    private static void assertClose(String what, double expected, double actual, double rel) {\n")
          .append("        double tol = Math.max(rel, Math.abs(expected) * rel);\n")
          .append("        Assertions.assertEquals(expected, actual, tol, what);\n")
          .append("    }\n\n");
    }

    private void model(ModelSpec spec, StringBuilder sb) {
        var body = new JavaModelWriter(package_name, class_name).write(spec);
        // reuse the builder body, re-indented as a private helper
        int start = body.indexOf("    public static OpticalModel build() {");
        int end = body.lastIndexOf("    }\n");
        sb.append("    private static OpticalModel build() {\n")
          .append(body, body.indexOf('\n', start) + 1, end)
          .append("    }\n\n");
    }

    private void first_order(Map<String, String> ref, StringBuilder sb) {
        sb.append("    @Test\n")
          .append("    public void first_order_data() {\n")
          .append("        var fod = build().optical_spec.parax_data.fod;\n");
        for (var e : sorted(ref, "fod.").entrySet()) {
            var name = e.getKey().substring("fod.".length());
            sb.append("        assertClose(\"fod.").append(name).append("\", ")
              .append(literal(e.getValue())).append(", fod.").append(name)
              .append(", ").append(EXACT_TOL).append(");\n");
        }
        sb.append("    }\n\n");
    }

    private void paraxial(Map<String, String> ref, StringBuilder sb) {
        sb.append("    @Test\n")
          .append("    public void paraxial_rays() {\n")
          .append("        var pd = build().optical_spec.parax_data;\n");
        for (var tag : new String[]{"ax", "pr"}) {
            var accessor = tag.equals("ax") ? "pd.ax_ray" : "pd.pr_ray";
            for (var e : sorted(ref, tag + ".").entrySet()) {
                var parts = e.getKey().split("\\.");
                var index = parts[1];
                var field = parts[2];
                sb.append("        assertClose(\"").append(e.getKey()).append("\", ")
                  .append(literal(e.getValue())).append(", ").append(accessor)
                  .append(".get(").append(index).append(").").append(field)
                  .append(", ").append(EXACT_TOL).append(");\n");
            }
        }
        sb.append("    }\n\n");
    }

    private void vignetting(Map<String, String> ref, StringBuilder sb) {
        var entries = sorted(ref, "fld.");
        if (entries.isEmpty())
            return;
        sb.append("    @Test\n")
          .append("    public void vignetting_factors() {\n")
          .append("        var fields = build().optical_spec.fov.fields;\n");
        for (var e : entries.entrySet()) {
            var parts = e.getKey().split("\\.");
            sb.append("        assertClose(\"").append(e.getKey()).append("\", ")
              .append(literal(e.getValue())).append(", fields[").append(parts[1])
              .append("].").append(parts[2])
              .append(", ").append(SOLVER_TOL).append(");\n");
        }
        sb.append("    }\n\n");
    }

    /**
     * Pins the chief ray aiming result per field. For a wide angle model this is
     * the only assertion that reaches find_real_enp_rev1 directly - vignetting
     * depends on it, but only at solver tolerance, so a regression there could
     * otherwise slip through.
     * <p>
     * Upstream overloads aim_info: a scalar z_enp in wide angle mode, an x,y aim
     * point otherwise. Beam43 splits it into Field.z_enp and Field.aim_info, so
     * the key that was recorded selects which one to check.
     */
    private void chief_ray_aiming(Map<String, String> ref, StringBuilder sb) {
        var entries = sorted(ref, "aim.");
        if (entries.isEmpty())
            return;
        sb.append("    @Test\n")
          .append("    public void chief_ray_aiming() {\n")
          .append("        var fields = build().optical_spec.fov.fields;\n");
        for (var e : entries.entrySet()) {
            var parts = e.getKey().split("\\.");
            var index = parts[1];
            var what = parts[2];
            if (what.equals("z_enp")) {
                sb.append("        Assertions.assertNotNull(fields[").append(index)
                  .append("].z_enp, \"").append(e.getKey()).append(" - expected wide angle aiming\");\n")
                  .append("        assertClose(\"").append(e.getKey()).append("\", ")
                  .append(literal(e.getValue())).append(", fields[").append(index)
                  .append("].z_enp, ").append(SOLVER_TOL).append(");\n");
            }
            else {
                var component = what.equals("x") ? "0" : "1";
                sb.append("        Assertions.assertNotNull(fields[").append(index)
                  .append("].aim_info, \"").append(e.getKey()).append(" - expected paraxial aiming\");\n")
                  .append("        assertClose(\"").append(e.getKey()).append("\", ")
                  .append(literal(e.getValue())).append(", fields[").append(index)
                  .append("].aim_info[").append(component).append("], ")
                  .append(SOLVER_TOL).append(");\n");
            }
        }
        sb.append("    }\n\n");
    }

    /**
     * Transverse ray aberration and OPD along the x and y pupil fans, per field
     * and wavelength. These are what the optimizer's ray-aberration and MTF
     * goals are built on, so they are the layer where a regression would show up
     * as a moved optimum rather than as an obviously wrong number.
     * <p>
     * The pupil coordinate is asserted alongside each value. Failed rays are
     * dropped rather than padded on the Java side, so if a ray that traced when
     * the reference was captured later fails, the fans stop being index aligned
     * - checking the pupil makes that surface as a failure instead of silently
     * comparing different rays.
     */
    private void aberration_fans(Map<String, String> ref, StringBuilder sb) {
        var entries = sorted(ref, "fan.");
        if (entries.isEmpty())
            return;
        // fan.<field>.<wavelength>.<xy>.<ray>.<quantity>
        Map<String, Map<Integer, double[]>> fans = new LinkedHashMap<>();
        for (var e : entries.entrySet()) {
            var p = e.getKey().split("\\.");
            var fan_key = p[1] + "." + p[2] + "." + p[3];
            var ray = Integer.parseInt(p[4]);
            var slot = switch (p[5]) {
                case "pupil" -> 0;
                case "t_abr" -> 1;
                case "opd" -> 2;
                default -> throw new IllegalArgumentException("Unknown fan quantity " + p[5]);
            };
            fans.computeIfAbsent(fan_key, k -> new java.util.TreeMap<>())
                .computeIfAbsent(ray, k -> new double[3])[slot] = Double.parseDouble(e.getValue());
        }

        sb.append("    @Test\n")
          .append("    public void aberration_fans() {\n")
          .append("        var opm = build();\n")
          .append("        var options = new TraceOptions();\n");
        for (var fan : fans.entrySet()) {
            var p = fan.getKey().split("\\.");
            var fi = p[0];
            var wi = p[1];
            var xy = p[2];
            var tag = "f" + fi + "w" + wi + "xy" + xy;
            sb.append("\n        var abr").append(tag)
              .append(" = TransverseRayAberrationAnalysis.eval_abr_fan(opm, ").append(fi)
              .append(", ").append(xy).append(", ").append(fan.getValue().size())
              .append(", false, options).fans.get(").append(wi).append(");\n")
              .append("        var opd").append(tag)
              .append(" = WavefrontAberrationAnalysis.eval_opd_fan(opm, ").append(fi)
              .append(", ").append(xy).append(", ").append(fan.getValue().size())
              .append(", false, options).fans.get(").append(wi).append(");\n")
              .append("        Assertions.assertEquals(").append(fan.getValue().size())
              .append(", abr").append(tag).append(".fan_y.size(), \"fan ").append(fan.getKey())
              .append(" ray count\");\n");
            for (var ray : fan.getValue().entrySet()) {
                var i = ray.getKey();
                var v = ray.getValue();
                var label = "fan." + fan.getKey() + "." + i;
                sb.append("        assertClose(\"").append(label).append(".pupil\", ")
                  .append(JavaModelWriter.num(v[0])).append(", abr").append(tag)
                  .append(".fan_x.get(").append(i).append("), ").append(SOLVER_TOL).append(");\n")
                  .append("        assertClose(\"").append(label).append(".t_abr\", ")
                  .append(JavaModelWriter.num(v[1])).append(", abr").append(tag)
                  .append(".fan_y.get(").append(i).append("), ").append(SOLVER_TOL).append(");\n")
                  .append("        assertClose(\"").append(label).append(".opd\", ")
                  .append(JavaModelWriter.num(v[2])).append(", opd").append(tag)
                  .append(".fan_y.get(").append(i).append("), ").append(SOLVER_TOL).append(");\n");
            }
        }
        sb.append("    }\n\n");
    }

    private void seidel(Map<String, String> ref, StringBuilder sb) {
        var entries = sorted(ref, "seidel.");
        if (entries.isEmpty())
            return;
        // group by row label: "11", "11.asp", "sum"
        Map<String, double[]> rows = new LinkedHashMap<>();
        for (var e : entries.entrySet()) {
            var rest = e.getKey().substring("seidel.".length());
            int split = rest.lastIndexOf('.');
            var row = rest.substring(0, split);
            var col = rest.substring(split + 1);
            rows.computeIfAbsent(row, k -> new double[5])[column_index(col)] =
                    Double.parseDouble(e.getValue());
        }
        sb.append("    @Test\n")
          .append("    public void seidel_coefficients() {\n")
          .append("        var opm = build();\n")
          .append("        var third_order = ThirdOrder.compute_third_order(opm);\n")
          .append("        double[] sum = new double[5];\n")
          .append("        for (ThirdOrderData d : third_order.values()) {\n")
          .append("            accumulate(sum, d.seidel());\n")
          .append("            if (d.has_aspheric())\n")
          .append("                accumulate(sum, d.aspheric());\n")
          .append("        }\n");
        for (var e : rows.entrySet()) {
            var row = e.getKey();
            var v = e.getValue();
            if (row.equals("sum")) {
                emit_row(sb, "seidel.sum", "sum", v);
            }
            else if (row.endsWith(".asp")) {
                var surf = row.substring(0, row.length() - ".asp".length());
                sb.append("        var asp").append(surf)
                  .append(" = third_order.get(").append(surf).append(").aspheric();\n");
                emit_row(sb, "seidel." + row, "asp" + surf, v);
            }
            else {
                sb.append("        var s").append(row)
                  .append(" = third_order.get(").append(row).append(").seidel();\n");
                emit_row(sb, "seidel." + row, "s" + row, v);
            }
        }
        sb.append("    }\n\n")
          .append("    private static void accumulate(double[] into, double[] add) {\n")
          .append("        for (int i = 0; i < into.length; i++)\n")
          .append("            into[i] += add[i];\n")
          .append("    }\n\n");
    }

    private void emit_row(StringBuilder sb, String label, String var, double[] v) {
        String[] names = {"S-I", "S-II", "S-III", "S-IV", "S-V"};
        for (int i = 0; i < 5; i++) {
            sb.append("        assertClose(\"").append(label).append(' ').append(names[i])
              .append("\", ").append(JavaModelWriter.num(v[i])).append(", ")
              .append(var).append('[').append(i).append("], ").append(EXACT_TOL).append(");\n");
        }
    }

    private static int column_index(String col) {
        return switch (col) {
            case "S-I" -> 0;
            case "S-II" -> 1;
            case "S-III" -> 2;
            case "S-IV" -> 3;
            case "S-V" -> 4;
            default -> throw new IllegalArgumentException("Unknown Seidel column " + col);
        };
    }

    /** Entries with the given prefix, ordered by surface index where present. */
    private static Map<String, String> sorted(Map<String, String> ref, String prefix) {
        Map<String, String> out = new TreeMap<>(JavaTestWriter::compare_keys);
        for (var e : ref.entrySet()) {
            if (e.getKey().startsWith(prefix))
                out.put(e.getKey(), e.getValue());
        }
        return out;
    }

    /** Sorts numeric path segments numerically so surface 10 follows surface 9. */
    private static int compare_keys(String a, String b) {
        String[] pa = a.split("\\."), pb = b.split("\\.");
        for (int i = 0; i < Math.min(pa.length, pb.length); i++) {
            int c;
            if (pa[i].matches("\\d+") && pb[i].matches("\\d+"))
                c = Integer.compare(Integer.parseInt(pa[i]), Integer.parseInt(pb[i]));
            else
                c = pa[i].compareTo(pb[i]);
            if (c != 0)
                return c;
        }
        return Integer.compare(pa.length, pb.length);
    }

    /** Python repr of a float parses as a Java literal once suffixed. */
    private static String literal(String value) {
        return JavaModelWriter.num(Double.parseDouble(value));
    }
}
